Issue 96
mekomsolutions/openmrs-module-initializer pull request #100
Opened 2021-04-09 07:08 UTC by suruchee

2021-04-09 15:31 UTC, ibacher commented
@suruchee The code looks fine to me. A couple of points:

1. This PR is marked as a draft; if you want it to be merged, it should be unmarked as a draft.
2. There's apparently a conflict between your branch and `master`. Could you please update your local branch to resolve the conflict?
3. Please title this PR something descriptive, e.g., "Support for OCL export ZIP file"
4. In the description for the PR it would be helpful to mention the OpenMRS ticket for it.

Once you've taken care of the above points, I'd ask Dmitri or someone with commit access to this repo to review this.

Thanks for your work on this!

2021-04-09 16:08 UTC, suruchee commented
Thanks @ibacher  for the review. I have updated with master and changed the PR title and description. 
Thank you so much for the support.

2021-04-12 17:44 UTC, mseaton reviewed
Just a few questions / comments on my end.  @mks-d interested to understand your perspective...

2021-04-12 17:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
This is very likely not the right spot for this.  The order of the loaders in the Domain need to be set based on dependencies.  As many other domains are dependent on Concept, the OCL domain (assuming we want a separate domain for this) should be adjacent to the concept domain.

2021-04-12 17:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
It's not 100% clear to me that we want "openconceptlab" to be a separate Domain from Concept.  I'd be interested in other's thoughts as to whether this is preferable, or whether having the Concepts domain capable of saying "if I find a file with .zip extension, then assume it's an OCL zip and try to import it using the OCL module.

2021-04-13 13:29 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
I haven't thought it through deeply, but would it make sense to keep it separate:

* in case OCL ends up packaging more than concepts, or because
*  in case we want to use "zip" packaging for the standard csv model

But just thoughts, for final decision I'm fine with what @mseaton  and @mks-d decide

2021-04-13 13:39 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
There are two small advantages I see to having a separate OCL domain (over and above what Mark said):

1. It keeps the documentation for both the OCL domain and the Concept domain simpler
2. It keeps the code to load concepts from OCL a bit simpler (because whether or not the loader is loaded at all depends on whether the OCL module is present or not; if we integrate this into the concept domain then we have to add a check for the OCL loader).

The biggest downside I see to having a separate domain is that we lose some flexibility with concept dependencies, i.e., either the OCL domain is loaded before the concept domain or its loaded after the concept domain, meaning that either the OCL domain or the Concept domain can't depend on concepts defined in the other domain to be present when loading. That said, I think OCL packaging is fairly self-contained so loading it before the Concept domain shouldn't have any issues.

I don't really have a strong opinion either way and would be happy to see this implemented as part of the concept domain if that's what @mks-d and @mseaton think is best.

2021-04-13 14:47 UTC, mks-d requested changes

2021-04-13 14:47 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/OpenConceptLabLoader.java
> +			importer = Context.getRegisteredComponent("openconceptlab.importer", Importer.class);
Please autowire rather than using `Context` static methods to get beans. That'll help you get rid of that `if`.

2021-04-13 14:47 UTC, mks-d commented on pom.xml
> +           <dependency>
There's a misindentation here.

2021-04-13 14:47 UTC, mks-d commented on pom.xml
> +		<openconceptlabVersion>1.2.6-SNAPSHOT</openconceptlabVersion>
There's a misindentation here.

2021-04-13 14:47 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			Concept c = Context.getConceptService().getConceptByUuid("4421da0d-42d0-410d-8ffd-47ec6f155d8f");
Autowire `ConceptService`.

2021-04-13 14:47 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		new OpenConceptLabActivator().setDaemonToken(daemonToken);
I guess the OCL importer needs this?

2021-04-13 14:47 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
The order should be either just before or just after that of concepts.

2021-04-13 14:47 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
Maybe
```java
OCL(32, "ocl")
```
?
As for the class and variable names I think I prefer the full wording, and that's what you have done 👍

2021-04-13 14:47 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		}
I think you should come up with a test .zip file that contains a couple of concepts (and not necessarily a full CIEL). Because then your asserts don't make much sense.

Export a couple of concepts in a .zip and **fully assert** that they have been loaded as expected in OpenMRS.

2021-04-13 14:52 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
I would vote for keeping them separate and load 'ocl' before 'concepts'.
That way 'concepts' could be used to overwrite 'ocl' if ever needed for whatever implementation or site-specific reason.

2021-04-13 17:05 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
Sounds good to me, thanks @mks-d

2021-04-16 08:05 UTC, suruchee commented
Thank you everyone for the review. @mks-d , I have made changes as you have suggested, can you please review it once again.

2021-04-16 08:19 UTC, mks-d requested changes
Again, in the same spirit as MDS, you will have to add your new `openconceptlab` dependency for the Validator, see here for MDS: https://github.com/mekomsolutions/openmrs-module-initializer/blob/e21ad7a277c05651f2d1cd24b4516772524ba7f0/validator/pom.xml#L169-L175

I also strongly suggest that you validate your work with the Validator btw.

2021-04-16 08:19 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/OpenConceptLabLoader.java
> +@OpenmrsProfile(modules = { "ocl:*" })
@suruchee this is most likely going to be
```java
@OpenmrsProfile(modules = { "openconceptlab:1.2.6-SNAPSHOT" })
```

2021-04-16 08:19 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/OpenConceptLabLoader.java
> +			importer = Context.getRegisteredComponent("openconceptlab.importer", Importer.class);
@suruchee did you see my comment above ↑?

2021-04-16 08:19 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		new OpenConceptLabActivator().setDaemonToken(daemonToken);
@suruchee did you see my comment above ↑?

2021-04-16 08:19 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			Concept c = conceptService.getConceptByUuid("5821b91383ac240007c3c0f3");
@suruchee `5821b91383ac240007c3c0f3` is an illegal UUID.

2021-04-16 08:19 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			Assert.assertEquals("Procedure", c.getConceptClass());
@suruchee surely there's a lot more that you want to assert, all the mappings typically.

You need to demonstrate that you can load a rich set of information about concepts. I would also go beyond just one concept.

Having said that, thanks for trimming down the test .zip.

2021-04-16 12:39 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		new OpenConceptLabActivator().setDaemonToken(daemonToken);
Yes. The actual loading is done in a daemon thread and the daemon token is fetched from the activator.

2021-04-16 15:49 UTC, suruchee commented
@mks-d,I have tried to improve tests, will you please review the changes?

2021-04-19 08:43 UTC, mks-d requested changes
Thanks @suruchee, a couple of changes/comments.

After addressing them it would be great is to validate that everything works _with_ the Validator. Should we try to liaise about this, maybe over the TAC call? @gracepotma?

2021-04-19 08:43 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersOrderTest.java
> +		Assert.assertThat(loader.getOrder(), greaterThan(previousLoader.getOrder()));
@suruchee this should be move up between those two lines: https://github.com/mekomsolutions/openmrs-module-initializer/pull/100/files#diff-5c58224096e13067818fadbb6a3f8c8ad7b7548c524f8acc80de7f4190f57b7aR220-R222

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		new OpenConceptLabActivator().setDaemonToken(daemonToken);
@ibacher does it need to involve the real activator or this could be done, see
* [Set a Daemon token in modules context-sensitive tests](https://talk.openmrs.org/t/set-a-daemon-token-in-modules-context-sensitive-tests/32022/5?u=mksd)

Makes me think that I never created the ticket for Core, I wonder if this could be scoped in and then used here?

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		}
@suruchee the reason for the anonymous scope here is so that you can keep redeclaring `Concept c` multiple times. So just do:
```java
{
    Concept c = conceptService.getConceptByUuid("db1741f033144371a191649f98454148");
    Assert.assertEquals("Text", c.getDatatype());
    Assert.assertFalse(c.getRetired());
}
```
Anyway, what is this test about, and why is there an illegal UUID (`db1741f033144371a191649f98454148`)?

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			c = conceptService.getConceptByName("VACCINE MANUFACTURER");
Change this to
```java
Concept c = conceptService.getConceptByName("VACCINE MANUFACTURER");
```
and assert each newly fetched concept in its own anonymous scope.

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			c = conceptService.getConceptByUuid("98b5c08e2069432da950878ccea81d19");
Illegal UUID?

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			c = conceptService.getConceptByUuid("ed92472255674a4095559f2e0daad26d");
Illegal UUID.

2021-04-19 08:43 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +			c = conceptService.getConceptByUuid("f1f09c2f1e164804bd80f5df9e7f8dac");
Illegal UUID.

2021-04-19 12:31 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +		new OpenConceptLabActivator().setDaemonToken(daemonToken);
It would involve some refactoring to leverage something like that. Currently the module is calling `OpenConceptLabActivator.getDaemonToken()` where it needs a daemon token. In any case, the constructor for the activator for the OCL module doesn't actually do anything.

2021-04-19 12:31 UTC, ibacher commented on pom.xml
> +        <!-- JUnit, Powermock  -->
This seems unnecessary?

2021-04-19 12:31 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	OCL(32, "openconceptlab");
@suruchee Per the discussion here, we should move this to before `CONCEPT` in the load order. Presumably this also means we need to renumber everything from `CONCEPT` -> `HTMLFORMS`.

2021-04-20 07:37 UTC, suruchee commented
@mks-d , I actually get confused with OCL UUID and Concept UUID, now I have updated with the required changes.

2021-04-20 08:07 UTC, mks-d requested changes
Thanks @suruchee.

I requested a change (I provided a snippet for it) on the main test class.
Also don't forget to address this: https://github.com/mekomsolutions/openmrs-module-initializer/pull/100#discussion_r615802730

I will have more comments on the tests though.

Finally we will have to look into proof testing all this with the validator as mentioned here: https://github.com/mekomsolutions/openmrs-module-initializer/pull/100#pullrequestreview-638589222

2021-04-20 08:07 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	}
@suruchee this is what I mean with using anonymous scopes for each block of assertion, you can copy/paste the below snipptet:
```java
@Test
public void load_shouldImportOCLPackages() {
    // Verif setup
    {
        Concept c = conceptService.getConceptByUuid("1419AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        Assert.assertEquals("Text", c.getDatatype());
        Assert.assertFalse(c.getRetired());
    }

    // Replay        
    loader.load();

    // Verif by name
    {
        Context.setLocale(localeEn);
        Concept c = conceptService.getConceptByName("VACCINE MANUFACTURER");
        Assert.assertNotNull(c);
        Assert.assertEquals(0, c.getDescriptions().size());
        Assert.assertEquals("Finding", c.getConceptClass().getName());
        Assert.assertEquals("Text", c.getDatatype().getName());
    }
    // Verify by UUID
    {
        Context.setLocale(localeEn);
        Concept c = conceptService.getConceptByUuid("3004BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
        Assert.assertNotNull(c);
        Assert.assertEquals("YELLOW FEVER VACCINATION", c.getName(localeEn).getName());
        Assert.assertEquals("Vaccine given for Yellow Fever.", c.getDescription().toString());
        Assert.assertEquals("Drug", c.getConceptClass().getName());
        Assert.assertEquals("N/A", c.getDatatype().getName());
    }
    // Verify in another locale
    {
        Context.setLocale(localeFr);
        Concept c = conceptService.getConceptByName("Fabricant du vaccin");
        Assert.assertNotNull(c);
        Assert.assertEquals(0, c.getDescriptions().size());
        Assert.assertEquals("Finding", c.getConceptClass().getName());
        Assert.assertEquals("Text", c.getDatatype().getName());;
    }
    // Verify just one name is enough
    {
        Context.setLocale(localeEn);
        Concept c = conceptService.getConceptByName("PNEUMOCOCCAL VACCINE");
        Assert.assertNotNull(c);
        Assert.assertEquals(3, c.getNames().size());
        Assert.assertEquals(0, c.getShortNames().size());
        Assert.assertEquals(0, c.getDescriptions().size());
        Assert.assertEquals("Drug", c.getConceptClass().getName());
        Assert.assertEquals("N/A", c.getDatatype().getName());;
    }
    // Failed ones
    {
        Context.setLocale(localeEn);
        Assert.assertNull(conceptService.getConceptByUuid("db2f5104-3171-11e7-93ae-92361f002670"));
        Assert.assertNull(conceptService.getConceptByName("MEASLES VACCINATION"));
        Assert.assertNull(conceptService.getConceptByName("db2f5460-3171-11e7-93ae-92361f002672"));
        Assert.assertNull(conceptService.getConceptByName("HEPATITIS B VACCINATION"));
        Assert.assertNull(conceptService.getConceptByUuid("00b29984-3183-11e7-93ae-92361f002679"));;
    }
    // Retired one
    {
        Concept c = conceptService.getConceptByUuid("83531AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        Assert.assertTrue(c.isRetired());;
    }
    // Un-retire one
    {
        Context.setLocale(localeEn);
        Concept c = conceptService.getConceptByUuid("17AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        Assert.assertNotNull(c);
        Assert.assertFalse(c.getRetired());
        Assert.assertEquals("DIPTHERIA TETANUS BOOSTER", c.getFullySpecifiedName(localeEn).getName());
        Assert.assertEquals("Drug", c.getConceptClass().getName());
        Assert.assertEquals("N/A", c.getDatatype().getName());
    }
    
}
```

2021-04-20 08:28 UTC, suruchee commented
@mks-d, Thanks for the guidance, is the last update fine?

2021-04-22 08:13 UTC, mks-d submitted a review, later dismissed
@suruchee I'll have to get a closer look at the tests by actually looking at the JSON file loaded in the first place (which I haven't had a chance to do yet.)

In the meantime, please add a further commit with all README stuff as it is done for all other domains.

2021-08-13 14:18 UTC, suruchee commented
@Ruhanga, I have updated resolving the conflicts, will you please have a look?

2021-08-20 07:24 UTC, Ruhanga requested changes

2021-08-20 07:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	    // Verif setup
Let's use Setup instead.

2021-08-20 07:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	    // Verif by name
Typo ➙ Verify

2021-08-20 07:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	    // Failed ones
Verify failures

2021-08-20 07:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	    // Retired one
Verify retirement

2021-08-20 07:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +	    {
Verify un-retirement

2021-08-23 08:06 UTC, suruchee commented
@Ruhanga, I have updated with your suggestions, will you please have a look?

2021-09-01 10:52 UTC, Ruhanga requested changes
Hi @suruchee, thanks for the update. Could you also rebase on the PR?

2021-09-01 10:57 UTC, Ruhanga reviewed
Could you also try the validator tool? Follow the documentation available [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/validator.md).

2021-09-03 08:38 UTC, suruchee commented
@Ruhanga , I have already added the validator.

2021-09-03 15:46 UTC, gracepotma commented
@suruchee what's the next step here, or what do you need next from Nathan or others...?

2021-09-05 16:13 UTC, Ruhanga commented
@suruchee, looks like there there are still merge conflicts in the file `api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersOrderTest.java`. Could you have rebased and failed to push the changes?

2021-09-06 04:48 UTC, suruchee commented
Thanks @Ruhanga for the review, I have updated resolving the conflict, will you have a look again?

2021-09-07 07:56 UTC, Ruhanga reviewed
@suruchee, does this branch build successfully locally your end? There seems to be some compilation error `openmrs-module-initializer/api/src/main/java/org/openmrs/module/initializer/api/loaders/OpenConceptLabLoader.java:[30,25] cannot access org.springframework.web.multipart.MultipartFile
`. Could you make sure the branch builds without errors?

2021-09-07 08:31 UTC, suruchee commented
@Ruhanga, this is a problem in ubuntu and only gets solved when spring framework dependency is added. But as you can also view from the previous conversation it is not recommended to use it. So, @ibacher, will you please have a look at it and help me solve it?

2021-09-07 09:25 UTC, Ruhanga requested changes

2021-09-07 09:25 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +>>>>>>> 6cadc0cb071b7a85cda86a4f975797cdc47ec5e9
@suruchee, could the problem be related to the conflicts not resolved here?

2021-09-07 10:29 UTC, suruchee commented on api/src/test/java/org/openmrs/module/initializer/api/OpenConceptLabLoaderIntegrationTest.java
> +>>>>>>> 6cadc0cb071b7a85cda86a4f975797cdc47ec5e9
Thank you @Ruhanga, I am sorry for missing out this file. I have updated after resolving the conflict. But the multipart issue still exists.

2021-09-07 12:45 UTC, Ruhanga reviewed
@suruchee, could you point me to the commit/changes introducing the error?

2021-09-07 15:17 UTC, suruchee commented
@Ruhanga, it worked until https://github.com/mekomsolutions/openmrs-module-initializer/pull/100/commits/4b4551ee146c16ea01ccc86a1758d0321ef38b42 , then I removed spring dependency.

2021-09-08 06:13 UTC, Ruhanga reviewed
@mks-d, @ibacher, I understand placing web related dependencies into the api layer as violating OpenMRS conventions. For some reason there is a hard requirement for this on [openconceptlab api](https://github.com/openmrs/openmrs-module-openconceptlab/blob/master/api/pom.xml#L24-L28). Maybe the fix should happen there or we have to the following dependency to iniz api;

```
      <dependency>
            <groupId>org.openmrs.web</groupId>
            <artifactId>openmrs-web</artifactId>
            <version>${openmrsPlatformVersion}</version>
            <scope>provided</scope>
      </dependency>
```

@suruchee, could you try with the above  added to `api/pom.xml` and ensure the tests pass?

2021-09-08 12:15 UTC, mseaton commented
> I understand placing web related dependencies into the api layer as violating OpenMRS conventions

Yes, I would recommend against this.  I haven't investigated, but it may be that we need to make changes to the ocl module in order to remove any web dependencies that it incorrectly has within it's api layer.

2021-09-08 12:53 UTC, ibacher commented
There are two things that the openconcept lab module gets from importing openmrs-web as a `provided` dependency:

1. Access to the `MultipartFile` class that's been mentioned here.
2. Access to Jackson to handle the JSON we get from OCL.

We already have several modules that depend on openmrs-web in the API part (as a `provided` dependency) in order to get access to the `MultipartFile` class, e.g., [attachments](https://github.com/openmrs/openmrs-module-attachments/blob/d2b421908419d6ce77696b5b81c9435a3f187fca/pom.xml#L65), [uiframework](https://github.com/openmrs/openmrs-module-uiframework/blob/d81c458c9bc5d55b4fbb1cecd60588f7f59d8b50/api/pom.xml#L28), and [htmlformentry](https://github.com/openmrs/openmrs-module-htmlformentry/blob/3839f633933ba96cabab6b538dd5b2049ae8ba5a/api/pom.xml#L36). I'm not meaning to suggest that this is the right way to go, just that this is how we've solved this need in the past.

For OpenMRS 1.9 (the earliest version we support in this module), Jackson is only available in openmrs-web as it wasn't moved to openmrs-api until 1.11 ([see TRUNK-3978](https://issues.openmrs.org/browse/TRUNK-3978)).

We could consider only supporting 1.11 or later instead of 1.9 or later, but that still doesn't help with the `MultipartFile` thing.

2021-09-08 13:21 UTC, mseaton commented
> We already have several modules that depend on openmrs-web in the API part

This was likely an inadvertent mistake that was made and we got away with it, but I don't think this is something we want to continue doing if we can avoid it.  Adding Jackson as a library to the initializer should be fine, right?

2021-09-08 14:33 UTC, ibacher commented
>  Adding Jackson as a library to the initializer should be fine, right?

It shouldn't be necessary to add Jackson to initializer or anything. Jackson is already available on the classpath at run time. I'm just explaining why it's a compile-time dependency for that module.

I suppose we can try to re-write things in the OCL module so we don't directly depend on `MultipartFile`, which would likely fix the issue here. I was just pointing out it's not a decision unique to the OCL module.

2021-09-10 06:53 UTC, Ruhanga reviewed
Thanks @ibacher and @mseaton. I created a ticket to address this on the jira OCLOMRS project [here](https://issues.openmrs.org/browse/OCLOMRS-1052). Could you make it ready for for work? Thanks.

@suruchee would you then be in position to take it up?

2021-09-10 08:36 UTC, suruchee commented
Yes, sure @Ruhanga .

2021-09-14 07:51 UTC, Ruhanga reviewed
@suruchee, are you able to progress with changes @ibacher has made on [OCLOMRS-1052](https://issues.openmrs.org/browse/OCLOMRS-1052)...

2021-09-17 09:11 UTC, Ruhanga commented
Hi @suruchee, how is this going?

2021-09-17 15:16 UTC, suruchee commented
Hi, @Ruhanga, I am working on it. I will update by monday.

2021-09-17 15:53 UTC, ibacher commented on pom.xml
> +        <openconceptlabVersion>1.2.6-SNAPSHOT</openconceptlabVersion>
So, to take advantage of the new changes, this should be bumped to 1.2.8. I'll release that in a second.

2021-09-20 13:14 UTC, suruchee commented
@Ruhanga , I will update the code once the maven repo gets fixed https://status.io/pages/incident/534decd528328a247100004b/6148696c733c3e0537440673

2021-09-21 11:17 UTC, Ruhanga reviewed
@suruchee, how is it going?

2021-09-21 11:50 UTC, suruchee commented
@Ruhanga, I have updated it, can you please review my last commit.

2021-09-21 12:02 UTC, Ruhanga reviewed
@suruchee, did you notice errors in the tests such as [this](https://pastebin.com/ybL6UieZ)?

2021-09-27 12:39 UTC, Ruhanga reviewed
Thanks for making progress on this @suruchee. How is it going at the moment with the tests?

2021-09-28 10:23 UTC, suruchee commented
@Ruhanga, I have tried adding few more tests and updating but the test still has some issues that I am not being able to solve. @ibacher, could you please help as I have already updated with the latest master?

2021-09-28 20:07 UTC, ibacher commented
@suruchee

Please verify that you're using the right data. For instance, the `load_shouldImportOCLPackages()` test tries to test for a concept with the UUID `3004BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB`. I'm not sure where that came from, but that's not a concept UUID (concept UUIDs in CIEL always end in `A`s; UUIDs ending in `B`s are concept names). The data in the Zip file can be found in [this gist](https://gist.github.com/ibacher/1cb11d8a2d63e983a03bdbd5686c5240).

I'm honestly not quite sure why the other tests are failing. Maybe it has something to do with the load order?

2021-09-29 10:56 UTC, suruchee commented
@ibacher, thanks for UUID idea and yes load order was causing issue, I have fixed load order and all tests but still I am getting a error which says:
Failed to load ApplicationContext getAttributeTypeByUuid_shouldGetAttributeType(org.openmrs.module.initializer.api.attributes.types.BahmniAttributeTypesProxyServiceTest): Failed to load ApplicationContext load_shouldLoadAccordingToCsvFiles(org.openmrs.module.initializer.api.BahmniAttributeTypesLoaderTest): Failed to load ApplicationContext

I don't think it's from OCL

2021-09-29 10:56 UTC, suruchee commented
@ibacher, thanks for UUID idea and yes load order was causing issue, I have fixed load order and all tests but still I am getting a error which says:
Failed to load ApplicationContext getAttributeTypeByUuid_shouldGetAttributeType(org.openmrs.module.initializer.api.attributes.types.BahmniAttributeTypesProxyServiceTest): Failed to load ApplicationContext load_shouldLoadAccordingToCsvFiles(org.openmrs.module.initializer.api.BahmniAttributeTypesLoaderTest): Failed to load ApplicationContext

I don't think it's from OCL

2021-09-29 17:09 UTC, Ruhanga commented
@suruchee, could you share the out put of a `mvn clean install`.

2021-09-30 08:10 UTC, suruchee commented
@Ruhanga, the output of mvn clean install is :
Tests in error: 
  saveAttributeType_shouldSaveAttributeType(org.openmrs.module.initializer.api.attributes.types.BahmniAttributeTypesProxyServiceTest): Failed to load ApplicationContext
  getAttributeTypeByUuid_shouldGetAttributeType(org.openmrs.module.initializer.api.attributes.types.BahmniAttributeTypesProxyServiceTest): Failed to load ApplicationContext
  load_shouldLoadAccordingToCsvFiles(org.openmrs.module.initializer.api.BahmniAttributeTypesLoaderTest): Failed to load ApplicationContext

2021-09-30 12:39 UTC, ibacher commented
@suruchee That's a different set of errors than I get with the code from this PR. Do you have local changes that aren't pushed yet? Also, it would be helpful to have more output than just the `Tests in error`, e.g., above them there should be tracebacks for where the errors actually occurred which is necessary to work out *why* those tests failed.

2021-10-04 09:57 UTC, suruchee commented
@ibacher, the output I am getting in mvn clean install is at https://pastebin.com/1beqLBLR, please have a look

2021-10-04 19:34 UTC, Ruhanga reviewed
@suruchee do you get the same errors when you `mvn clean install` on the updated master branch?

2021-10-05 11:08 UTC, suruchee commented
@Ruhanga, the updated master branch is running fine. My test has some problems but it's hard to find.

2021-10-20 16:27 UTC, mseaton commented
> I am getting an error https://pastebin.com/1beqLBLR

@suruchee (cc @ibacher and @mks-d) - the key part of that error message is this:

`Caused by: java.lang.NoSuchMethodError: javax.persistence.Table.indexes()[Ljavax/persistence/Index;`

Googling this error, [you can find this link](https://stackoverflow.com/questions/50573767/hibernate-5-java-lang-nosuchmethoderror-javax-persistence-table-indexes) which is indicates the likely cause of the issue.

Indeed, running `mvn dependency:tree` on your branch reveals this conflicting library within the api-bahmni submodule:

```
[INFO] +- org.ict4h:atomfeed-client:jar:1.9.4:test
[INFO] |  \- org.ict4h:atomfeed-commons:jar:1.9.4:test
[INFO] |     \- javax.persistence:persistence-api:jar:1.0.2:test
```
To fix this problem, you should change api-bahmni/pom.xml and add an additional exclusion (after the existing rome exclusion) as follows:

        <dependency>
            <groupId>org.ict4h</groupId>
            <artifactId>atomfeed-client</artifactId>
            <version>${atomfeed-client.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>rome</groupId>
                    <artifactId>rome</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.persistence</groupId>
                    <artifactId>persistence-api</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

2021-10-20 16:31 UTC, mseaton commented
@suruchee , based on my building of your branch, once you resolve the above issue in the pom and in the LoadersOrderTest that I highlighted, you will also find that you get errors in some existing tests - notably the ConceptLoaderIntegrationTest and the ConceptSourcesLoaderIntegrationTest, presumably due to the fact that the OCL zip file you are importing is changing the expected data in these tests in a way that they are not expecting.  You'll need to work through these unless we find a way to better isolate these tests from each other (I may create a separate ticket for this - @mks-d FYI)

2021-11-04 09:26 UTC, Ruhanga reviewed
@suruchee, how is it going?

2021-11-11 04:53 UTC, suruchee commented
Thanks @ibacher for the fix, all tests are passing now.

2021-11-11 14:52 UTC, suruchee commented
@Ruhanga, please have a look.

2021-11-15 09:02 UTC, Ruhanga reviewed
Thanks very much @suruchee, @ibacher. The tests are passing now. @suruchee, did/could you test the `ocl` domain against the [initializer-validator](https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/validator.md)?

2021-11-17 13:53 UTC, suruchee commented
@Ruhanga yes it's working fine.

2021-11-23 09:42 UTC, Ruhanga commented
> test the ocl domain against the [initializer-validator](https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/validator.md)?


@suruchee, did you run the validator as documented in the link above?

Something along the lines below
```
mvn clean package -P validator
```
```
java -jar validator/target/initializer-validator-2.3.0-SNAPSHOT.jar --config-dir=./api/src/test/resources/testAppDataDir/configuration --domains='ocl'
```
Could you try running those command to test the validator against the `ocl` domain and share the results you get?

2021-11-23 10:27 UTC, suruchee commented
@Ruhanga, I got an error while running against ocl the output is https://pastebin.com/EhZWtuVZ, will you please suggest me the suggestion?

2021-11-29 12:56 UTC, Ruhanga reviewed
@suruchee, a fix has been merged fixing the validator. Could you update this PR with the latest master changes and rerun the validator again? Please also provide the full logs from the run validator commands.

2021-12-01 06:03 UTC, suruchee commented
Hi @Ruhanga, thanks for the update. I have updated my branch with the latest master and ran the validator command but ended up with an error https://pastebin.com/nNBrPq9t please have a look

2022-01-07 13:34 UTC, mseaton commented
@mks-d / @Ruhanga / @suruchee - I think we need to prioritize merging this PR.  I've pulled this locally and run it, and I am able to build successfully, and I'm able to run the validator using the instructions that @Ruhanga linked to successfully (as far as I can tell, there i a lot of verbose output and warnings, but not obvious errors).

I also don't think getting every issue resolved with the validator is a blocker to getting this merged, and it is more important to get an initial pass at supporting OCL packages into a mainstream initializer release so that we can start actually testing it with real packages and real distributions.

If there are issues, we'll fix them, but they will be limited to the ocl domain anyway, so there is not much risk that we are introducing regressions here.

The code itself we are introducing in the Loader is dead simple - really just delegating to the OCL module, and supporting keeping that OCL zip in the configuration directories.

Can we merge this in ASAP please?

2022-01-07 13:54 UTC, ibacher commented
I'm in concurrence with @mseaton on this. The validator issues @suruchee indicated above aren't issues with validation per se, but issues with starting MariaDB4J itself (i.e., it's looking for the ncurses library which either isn't installed or the correct version isn't installed—realistically these binaries for MariaDB4J should be compiled completely statically if that's possible). Similarly on macOS, running the validator fails for me but because the command `mysql_install_db` fails with this message: "dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib". Again a DLL not being found in the expected place.

Practically speaking, I've run a version of Iniz using these commits and used it to successfully load data from an OCL ZIP into an OpenMRS instance, which is the practical end of what we're trying to do so delaying this due to tooling issues seems... counter-productive.

2022-01-14 16:45 UTC, ibacher commented
Since this now as been updated to work with the validator, merging this in.

2022-01-14 16:45 UTC, merged