Leave existing non-specified attributes and location tags intact when loading
mekomsolutions/openmrs-module-initializer pull request #104
Opened 2021-05-04 22:07 UTC by brandones

As discussed on Slack.

2021-05-05 21:27 UTC, mseaton reviewed
Defer to @mks-d for approval overall.  A few comments from me just doing a cursory review.

2021-05-05 21:27 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +			loc.setTags(null);
I wouldn't think we would need this line moved here, since the line immediately after is also calling setTags.

2021-05-05 21:27 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +				} else if (Boolean.TRUE.equals(location.hasTag(tagName))) {
This feels a little awkward.  I'd probably just go with else { if (location.hasTag(tagName)) { ... } }

2021-05-06 16:55 UTC, brandones commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +			loc.setTags(null);
```suggestion
```

2021-05-06 16:57 UTC, brandones commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +				} else if (Boolean.TRUE.equals(location.hasTag(tagName))) {
Unfortunately `location.hasTag` returns a `Boolean` rather than a `boolean`, so it can be null.

2021-05-12 08:28 UTC, mks-d requested changes

2021-05-12 08:28 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +				} else if (Boolean.TRUE.equals(location.hasTag(tagName))) {
@brandones try this:
```java
import static org.apache.commons.lang.BooleanUtils.isTrue;

...

private void setLocationTagsFromPrefixHeaders(Location location, CsvLine line) {
    for (String header : line.getHeaderLine()) {
        if (StringUtils.startsWithIgnoreCase(header, HEADER_TAG_PREFIX)) {
            String tagName = StringUtils.removeStartIgnoreCase(header, HEADER_TAG_PREFIX);
            LocationTag tag = locationService.getLocationTagByName(tagName);
            if (tag == null) {
                throw new IllegalArgumentException("The location tag header '" + header
                        + "' references a location tag that does not exist: '" + tagName + "'.");
            }
            
            if (isTrue(line.getBool(header))) {
                location.addTag(tag);
            } else if (isTrue(location.hasTag(tagName))) {
                location.removeTag(tag);
            }
        }
    }
}
```
(I also edited the exception message.)

2021-05-12 22:07 UTC, brandones commented
Incorporated your suggestion @mks-d

2021-05-13 10:54 UTC, mks-d reviewed
Thanks @brandones I think I'm good with this. Just two things:
1. A line on the 2.2 release notes of the README.
2. Could you create an issue for this work to be expanded to all domains/headers? So that it's on the roadmap.

2021-05-13 17:00 UTC, brandones commented
Ok, documented!

2021-05-14 11:02 UTC, mks-d approved these changes

2021-05-14 11:03 UTC, merged