[ #108 ]: Initializer should support configuration of different loadi…
mekomsolutions/openmrs-module-initializer pull request #109
Opened 2021-05-07 13:36 UTC by mseaton

…ng modes at startup

2021-05-12 14:16 UTC, mks-d reviewed
Thanks @mseaton, just requested a couple of minor changes.

2021-05-12 14:16 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/MockLoader.java
> +	public MockLoader(Domain domain, boolean throwException) {
Maybe a little JavaDoc here for this `throwException` arg?

2021-05-12 14:16 UTC, mks-d commented on readme/rtprops.md
> +This is exactly the same logic as for the Initializer Validator's `--domains` argument.
I guess this was pasted by mistake.

2021-05-13 13:16 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
> +		String startingLoadingMode = getInitializerService().getInitializerConfig().getStartupLoadingMode();
Fixed, see latest commit.

2021-05-13 13:17 UTC, mseaton commented on README.md
> +* (_Bug fix_) CSV domains can create new objects that are retired
Merged up master, and removed what I had put

2021-05-13 13:17 UTC, mseaton commented on api/src/test/java/org/openmrs/module/initializer/InitializerActivatorTest.java
> +	}
Don't entirely understand what you are asking for, but I changed the tests to _maybe_ get at what you are thinking?

2021-05-13 13:18 UTC, mseaton commented on api/src/test/java/org/openmrs/module/initializer/api/MockLoader.java
> +	public MockLoader(Domain domain, boolean throwException) {
Done

2021-05-13 13:18 UTC, mseaton commented on readme/rtprops.md
> +This is exactly the same logic as for the Initializer Validator's `--domains` argument.
Oops, yes removed.

2021-05-13 13:18 UTC, mseaton commented
@mks-d I've pushed up some changes in response to your comments.

2021-05-17 11:17 UTC, mks-d requested changes
_Very_ minor change, then we're good to go.

2021-05-17 11:17 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
> +		return Context.getService(InitializerService.class);
I just reorganised it slightly and used existing constants:
```java
public void started() {
    
    log.info("Start of " + MODULE_NAME + " module.");
    
    // setup logging
    {
        org.apache.log4j.Logger logger = org.apache.log4j.Logger
                .getLogger(InitializerActivator.class.getPackage().getName());
        logger.addAppender(
            Utils.getFileAppender(Paths.get(OpenmrsUtil.getApplicationDataDirectory(), MODULE_ARTIFACT_ID + ".log")));
        logger.setLevel(Level.WARN);
    }

    // loading according to startup mode
    String startupLoadingMode = getInitializerService().getInitializerConfig().getStartupLoadingMode();
    if (PROPS_STARTUP_LOAD_DISABLED.equalsIgnoreCase(startupLoadingMode)) {
        log.info("OpenMRS config loading process disabled at " + MODULE_NAME + " startup.");
    }
    else {
        try {
            log.info("OpenMRS config loading process started...");
            getInitializerService().loadUnsafe(true, PROPS_STARTUP_LOAD_FAIL_ON_ERROR.equalsIgnoreCase(startupLoadingMode));
            log.info("OpenMRS config loading process completed successfully.");
        }
        catch (Exception e) {
            throw new ModuleException("An error occurred when loading OpenMRS config.", e);
        }
    }
    
}
```

2021-05-17 13:45 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
> +		return Context.getService(InitializerService.class);
It took me a while to figure out what exactly you wanted changed!  Did you push this fix already?  Feel free to push to the branch - that's likely easier than the back and forth, especially since you normally do the merging anyway, but if you want me to make this change I can @mks-d ...

2021-05-17 16:45 UTC, mks-d approved these changes

2021-05-17 16:45 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
> +		return Context.getService(InitializerService.class);
@mseaton I can't push on your dev branch but I'll push later. It's just a slight reorganisation of the Activator that doesn't change much. Just me being finicky, sorry.

2021-05-17 16:49 UTC, merged