Adding support for bahmni program attribute types
mekomsolutions/openmrs-module-initializer pull request #133
Opened 2021-08-31 06:32 UTC by Ruhanga

2021-09-07 10:15 UTC, rbuisson requested changes
Thanks for this PR. Few small details plus missing the Readme.

2021-09-07 10:15 UTC, rbuisson commented on api/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitiveTest.java
> +				Module mod = new Module("", "bahmnicore", "", "", "", "0.93-SNAPSHOT");
Since we're bringing `0.94-SNAPSHOT` at runtime, let's just change that to `0.94-SNAPSHOT` too for consistency.

2021-09-07 10:15 UTC, rbuisson commented on api/src/test/resources/testAppDataDir/configuration/attributetypes/attribute_types.csv
> +9398c839-4f39-428c-9022-e457980ccfa8,,Program,CodedConcept attribute type,This is a Program's CodedConcept attribute type,0,1,org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype
Could you provide a `Datatype config` value (anything, maybe simply a UUID) here for documentation purposes?

2021-09-07 10:15 UTC, rbuisson commented on api-bahmni/src/test/java/org/openmrs/module/initializer/api/BahmniAttributeTypesLoaderTest.java
> +
remove new line

2021-09-10 11:39 UTC, rbuisson requested changes
@Ruhanga , as per my last review: missing the readme

2021-09-10 11:47 UTC, rbuisson reviewed
The project doesn't build for me:
```
[ERROR] Failed to execute goal on project initializer-api-bahmni: Could not resolve dependencies for project org.openmrs.module:initializer-api-bahmni:jar:2.2.0-SNAPSHOT: Could not find artifact org.bahmni.module:bahmnicore-api:jar:0.94-SNAPSHOT in openmrs-repo (https://mavenrepo.openmrs.org/nexus/content/repositories/public) -> [Help 1]
```
Did you get similar issues?
Could you try to build having removed your cached Bahmni Core artifacts?

2021-09-12 05:30 UTC, Ruhanga reviewed
@rbuisson, I think the artefact is not published to maven repositories. @reagan-meant had the same issue and had to build bahmnicore locally as well.

2021-09-13 08:55 UTC, rbuisson commented
I see.
Could you set the dependency to `<bahmniCoreVersion>0.93-1.1.0-SNAPSHOT</bahmniCoreVersion>`?
This points to Mekom's fork of Bahmni Core, which is almost identical as the community Bahmni Core, but on which we have control on and is available on nexus.mekomsolutions.net

2021-09-13 17:06 UTC, Ruhanga commented on api-bahmni/pom.xml
> +            <version>1.1.3</version>
No, I inherited the minimum version expected by bahmni-core, I've updated to the one provided by iniz.

2021-09-13 17:08 UTC, Ruhanga commented on api-bahmni/pom.xml
> +        <emrapi-omod.version>1.23.0</emrapi-omod.version>
I'd think no for now, because it is introduced mainly because it's required by bahmni-core and so only introducing it here.

2021-09-13 17:21 UTC, Ruhanga commented on api-bahmni/pom.xml
> +            <version>1.0-SNAPSHOT</version>
Done

2021-09-13 19:55 UTC, rbuisson approved these changes
Thanks. Looks good.

2021-09-13 19:59 UTC, merged