[#150] Add support for AMPATH Forms.
mekomsolutions/openmrs-module-initializer pull request #152
Opened 2021-10-27 19:49 UTC by reagan-meant

2021-11-12 19:22 UTC, ibacher requested changes

2021-11-12 19:22 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		clobData.setUuid(uuidAsString);
Unless it's a requirement, it seems like the UUIDs for the form, the form resource, and the clob data should be distinct from one another.

2021-11-15 06:09 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	AMPATH_FORMS,
@ibacher Should I attempt to add the validation in this PR?

2021-11-15 06:13 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +				clobData = datatypeService
Done

2021-11-15 06:13 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		if (formName == null) {
Done

2021-11-15 06:15 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +				formService.retireForm(form, "Retired by Iniz for new version");
Done

2021-11-15 07:32 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		UUID randomUUID = UUID.randomUUID();
Done

2021-11-15 07:34 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		clobData.setUuid(uuidAsString);
Fixed

2021-11-15 07:42 UTC, enyachoke commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +				if (formVersion.compareTo(form.getVersion()) < 0) {
@ibacher  Ampath forms does not enforce any format for the version

2021-11-15 08:56 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	AMPATH_FORMS,
@reagan-meant not yet as part of this PR, but we will subsequently attached a validation mechanism to loading AMPATH Forms, and this will have to work with the Validator.

2021-11-15 14:12 UTC, rbuisson commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		UUID randomUUID = UUID.randomUUID();
> We should also probably have a check for whether a form with that UUID already exists.

@ibacher Should we assume that if the UUID exists already we just not load the form, and fail?
I'm saying this because it looks like we shouldn't have the UUID field behave as a "unique identifier" for forms - as it does for other regular domains. This is because we are already leveraging on using the pair `Name + Version` to identify a given form. And at same the time identify if we should _edit_ VS _update with new version._

The current behavior implemented by Reagan I think is:
- Form exists with same name and same version -> edit existing form.
- Form exists with same name but older version -> update the form, ie, retire all other forms with the same name and create a new one

However if we say that we don't use `Name + Version` to identify a form, as you suggest in other comments, because the version format can't be trusted (non semver), then we could want to use the UUID to define if a form must be edited VS updated.
- Form exists with same name and same UUID -> edit
- Form exists with same name but different UUID -> update, ie, retire all other forms with the same name and create a new one with **incremented version number**)

It sounds like it's one **or** the other: Version **or** UUID. But we have to choose.

I would tend to think that the UUID makes things more complicated and less intuitive. And that leveraging on Name + Version is good enough. Thus we could simply ignore the UUID field.

2021-11-17 14:14 UTC, rbuisson commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		UUID randomUUID = UUID.randomUUID();
I think I get your point now.
So the UUID being computed based on "Constant + Name + Version" it would change obviously when the version changes...

From the implementer perspective, he could change the version number to something higher in order to publish a new version of the form. I guess it means we must still fetch all forms for that name and retire them, correct?

2021-11-22 18:37 UTC, rbuisson commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java
> +		UUID randomUUID = UUID.randomUUID();
Thanks @ibacher and @reagan-meant for the not-so-quick call 😀

Here is what we've decided:
- UUID will be generated based on name + version.
- **(case 1)** If a form with the same UUID is found already existing in the DB, it will be overriden by the form brought by Iniz
- **(case 2)** If a form with the same name is found but not the same UUID (or not the same version - which is the same thing), we retire it, and create a new form

In **case 2**, we only retire the single form returned by the `getFormByName()` method. We don't look at other forms that may have been already there and are not retired.

Let me know if all is clear @reagan-meant  for you to move forward.

2021-12-06 21:21 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	AMPATH_FORMS,
@reagan-meant I think the only thing that needs to be done is to move this to later in the load order. Then I think this looks fine.

2021-12-07 06:38 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	AMPATH_FORMS,
@ibacher this is fixed now

2021-12-09 19:18 UTC, ibacher commented
Alright! I'm happy with this! Just needs some docs!

2021-12-13 19:05 UTC, ibacher approved these changes

2021-12-13 19:05 UTC, merged