Issue 165
mekomsolutions/openmrs-module-initializer pull request #166
Opened 2021-12-10 17:29 UTC by mseaton

2021-12-21 12:25 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +		}
`line.get(header, true)` would [throw](https://github.com/mekomsolutions/openmrs-module-initializer/blob/5098c1058cb710ce683dde8dca7aba877e0f2ef8/api/src/main/java/org/openmrs/module/initializer/api/CsvLine.java#L50) if the header wasn't found no?

Don't you precisely want to do the contrary: use `line.get(header, false)` and if the value is `null` proceed through to the props?

2021-12-21 12:25 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +				throw new IllegalArgumentException(header + " is required but property " + property + " is not found");
To make the logs slightly more readable:
```
header + " is required but property '" + property + "' is not found."
```

2021-12-21 12:25 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +		if (val.toLowerCase().startsWith("property:")) {
Could we choose from either of
* `"application property:"`
* `"system property:"`
* `"runtime property:"` 

?
Or you think that none are appropriate?

If there is an appropriate one then this would lead to renaming the method as well to, for example, `getApplicationProperty`.

2021-12-21 12:25 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +	 */
This is nice meat for the README file, as for the JavaDoc it should just says what it does:

>Attempts to read the value from the CSV line as usual or falls back to reading the specified system or runtime property. Eg "property:foo" will attempt to read first the system property named "foo" or eventually the runtime property named "foo".

2021-12-27 23:09 UTC, mseaton commented
I've addressed a number of your comments and added responses to the rest @mks-d .  Let me know thoughts on getting this merged.

2022-02-07 18:45 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +				throw new IllegalArgumentException(header + " is required but property " + property + " is not found");
```suggestion
				throw new IllegalArgumentException(header + " is required but property '" + property + "' is not found");
```

2022-02-07 18:47 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/idgen/RemoteIdentifierSourceLineProcessor.java
> +		}
@mks-d As I read it, the intention is to have `property:<some_property_name>` in the line and replace that with the value gotten by looking up the property.

2022-02-07 19:21 UTC, ibacher approved these changes
@mseaton Thanks for this. It looks good to me. Just need to confirm with the validator.

2022-02-07 19:24 UTC, ibacher requested changes
Need to change things so the validator works, i.e., the domain can really be executed.

2022-02-07 21:41 UTC, mseaton commented
@ibacher - does the validator work for the idgen domain when run by itself _prior_ to this commit?  This commit doesn't introduce the domain, and I'm curious if this error was pre-existing...

2022-02-08 05:16 UTC, Ruhanga commented
>does the validator work for the idgen domain when run by itself
I'd think no @mseaton, because of some meta-data the domain depends on that is not yet in the database for example the `Identifier type`. For this you'd want to load all the metadata necessary for the domain to load successfully.

2022-02-08 12:37 UTC, ibacher commented
@mseaton @Ruhanga Yeah, that's fair. I was hoping to quickly verify that everything was ok and didn't have much of an opportunity to dig into why it failed. Looking into that now.

2022-02-08 14:33 UTC, ibacher commented
I get a very similar set of errors if I don't restrict the domain, but then again, they also appear on `master` so I'm assuming it's not the fault of this PR per se.

2022-02-08 19:11 UTC, mseaton commented
Thanks @ibacher - so would that imply that we don't need to fix that validator issue to merge this PR?  Since the issue in question already exists and we can ticket independently?

2022-02-08 19:42 UTC, ibacher commented
@mseaton Yes, that's the case. I just want to do a test on my end and then I think this can be merged.

2022-03-03 21:25 UTC, merged