ISSUE-170: 'Appointmentservicetypes' domain should not fetch by name
mekomsolutions/openmrs-module-initializer pull request #178
Opened 2022-02-14 14:46 UTC by reagan-meant

2022-02-14 17:15 UTC, ibacher reviewed
Thanks @reagan-meant! Code looks good. Two small things:

1. The issue is #177 not #170.
2. Does this work if no UUID is assigned? If not, we should update the docs to note that UUID needs to be assigned an throw an appropriate exception if none is provided.

2022-02-15 07:19 UTC, reagan-meant commented
@ibacher I think it is not a must to set a uuid

2022-02-15 13:30 UTC, rbuisson commented
> @ibacher I think it is not a must to set a uuid

@reagan-meant If that's not a must, then isn't it suppose to try fetch by name when no UUID is provided?
That does not make sense. We prob should make it mandatory to provide a UUID if we can't assume the name to be unique.

2022-02-17 08:50 UTC, rbuisson requested changes

2022-02-17 08:50 UTC, rbuisson commented on api/src/main/java/org/openmrs/module/initializer/api/appt/servicetypes/AppointmentServiceTypesCsvParser.java
> +			throw new IllegalArgumentException("Uuid should be set");
Please use the same message format as here: https://github.com/mekomsolutions/openmrs-module-initializer/blob/7a2b7c6d532d3dc27457604c1a5308f0fcc311a4/api/src/main/java/org/openmrs/module/initializer/api/providerroles/ProviderRolesCsvParser.java#L33

2022-02-17 12:29 UTC, ibacher commented on api/src/test/resources/testAppDataDir/configuration/appointmentservicetypes/servicetypes.csv
> +,2526359e-cb9e-45d4-b83a-2b588744eb05,Complex Bracing,6b220700-4ba2-4846-86a7-a2afa5b6f2eb,75,
```suggestion
,2526359e-cb9e-45d4-b83a-2b588744eb05,Complex Bracing,6b220700-4ba2-4846-86a7-a2afa5b6f2eb,75,

```

2022-02-17 12:31 UTC, ibacher approved these changes

2022-02-17 12:55 UTC, merged