[#101]: Adding domain for Liquibase changesets
mekomsolutions/openmrs-module-initializer pull request #179
Opened 2022-02-22 17:32 UTC by Ruhanga

See #101

2022-02-22 18:47 UTC, mseaton requested changes

2022-02-22 18:47 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
> +			updateDatabase(file.getPath());
The only thing you should need to do here is defer to OpenMRS.  Simply use the "org.openmrs.util.DatabaseUpdater" class from OpenMRS core:
```
DatabaseUpdater.executeChangelog(file.getPath(), null);
```

2022-02-23 06:26 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
> +			updateDatabase(file.getPath());
Ohhh, yes indeed @mseaton. I missed this one, thank you very much for pointing it out.

2022-02-24 09:14 UTC, rbuisson requested changes

2022-02-24 09:14 UTC, rbuisson commented on readme/liquibase.md
> +The **liquibase** subfolder contains liquibase configuration files for the purpose of updating difficult to predetermine metadata before they can be consumed safely. The underlying files may contain
Let's make sure Liquibase is written with a capital L where appripriate (anything else than the folder or domain name).
And:
> contains liquibase configuration files

"contains Liquibase changelog files"

2022-02-28 13:24 UTC, mseaton approved these changes
Looks good to me, though I did add a few comments for consideration.

2022-02-28 13:24 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
> +			Context.clearSession();
Did you determine that these calls to flush and clear session are necessary / useful?

2022-02-28 13:24 UTC, mseaton commented on readme/liquibase.md
> +The purpose for this domain is to provide updates on metadata and not any database schema. This for example, could be used to ensure all desired metadata is deterministic in nature with known `id`s/`
Why are we making this qualification?  We use liquibase in our configuration at PIH for all sorts of things - data migrations, creation of indexes, views, and functions for use in reports, etc.  To me the purpose is to allow implementations to execute database updates without having to write and deploy a heavy module just to deliver a liquibase changeset.  Let's leave the how and why to implementations to figure out.

2022-02-28 13:24 UTC, mseaton commented on readme/liquibase.md
> +  └── concepts.xml
It needs to be much clearer that "liquibase.xml" is what is required and expected.  Something like "concepts.xml" that would be referred to is supported, sure, but it's not the primary use case and should not be the focus of the documentation.  At PIH, we only use 1 xml file, but it refers to many SQL files by relative path.  Might be better off just linking to the liquibase documentation with a blurb about how liquibase.xml is required as the starting point, but that liquibase allows for changesets to refer to other changesets and external resources.

2022-02-28 14:42 UTC, ibacher requested changes
Definitely need to look into why the [test for this is failing|https://github.com/mekomsolutions/openmrs-module-initializer/runs/5318128314?check_suite_focus=true#step:4:7442] on CI before this can be merged. Otherwise, just some minor comments.

2022-02-28 14:42 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/LiquibaseLoaderIntegrationTest.java
> +		// Verif
```suggestion
		// Verify
```

2022-02-28 14:42 UTC, ibacher commented on api/src/test/resources/testAppDataDir/configuration/liquibase/liquibase.xml
> +</databaseChangeLog>
```suggestion
</databaseChangeLog>

```

2022-02-28 14:42 UTC, ibacher commented on readme/liquibase.md
> +	<changeSet id="jUnit-2022-02-22-12-51" author="test">
At least in documentation, it's better to use a better example:

```suggestion
	<changeSet id="ensure_admission_encountertype_uuid-202202221251" author="test">
```

2022-02-28 15:25 UTC, Ruhanga commented on readme/liquibase.md
> +The purpose for this domain is to provide updates on metadata and not any database schema. This for example, could be used to ensure all desired metadata is deterministic in nature with known `id`s/`
>This for example, could be used to ensure all desired metadata is deterministic in nature with known `id`s/`uuid`s before it's/they are usable/reference-able.

The above little doc is a simple example use-case that could help a non-liquibase acquainted  user of the module.

2022-02-28 15:27 UTC, Ruhanga commented on readme/liquibase.md
> +  └── concepts.xml
A link to the Liuqibase docs is actually way much handy indeed. I'll add a reference link. Thanks @mseaton.

2022-03-01 08:30 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
> +			Context.clearSession();
Thanks for the review @mseaton. I thought it safe since I've not gone through all edge-case scenarios. I'd be happy to remove those methods if this has not posed any problems based on your usage of `DatabaseUpdater .executeChangelog()`.

2022-03-01 10:25 UTC, Ruhanga commented on readme/liquibase.md
> +The purpose for this domain is to provide updates on metadata and not any database schema. This for example, could be used to ensure all desired metadata is deterministic in nature with known `id`s/`
Implementations are not restricted either from building their own complex Liquibase scripts in the end.

2022-03-01 10:32 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/LiquibaseLoaderIntegrationTest.java
> +		// Verif
>[test for this is failing](https://github.com/mekomsolutions/openmrs-module-initializer/runs/5318128314?check_suite_focus=true#step:4:7442)

Tests pass locally and there are no related runtime excepts. I'm not sure why this is only happening with github-actions. Would you help look into this @rbuisson, maybe @ibacher? Thanks.

2022-03-01 12:55 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
> +			Context.clearSession();
@Ruhanga yes, I would say remove those lines.  We don't do anything like that.  Liquibase doesn't have anything to do with Hibernate - it executes directly against a separate database connection - so flushing and clearing the Hibernate session is not something that should be done here.

2022-03-01 20:58 UTC, ibacher approved these changes

2022-03-03 21:24 UTC, merged

2022-03-04 11:55 UTC, mks-d commented
@ibacher / @Ruhanga this will require a follow-up commit that provides all the necessary README additions and creations.

2022-03-04 15:20 UTC, ibacher commented
@mks-d Whoops. Done in 1a8dcd4.