support-ampath-translations: Ampath Translations Loader added.
mekomsolutions/openmrs-module-initializer pull request #191
Opened 2022-07-22 15:15 UTC by icrc-jofrancisco

Support for loading AMPATH translation files using the initializer.
The file will be saved as ClobDatatypeStorage in order to support multiple forms.

2022-09-06 13:32 UTC, rbuisson commented
@icrc-jofrancisco , I guess the domain would be better named "Ampath Forms Translations"

2022-11-08 19:16 UTC, gracepotma commented
Perhaps @ibacher could review this?

2022-11-21 17:28 UTC, mks-d requested changes
Thanks @icrc-jofrancisco, however we need a couple of things:
1. Unit tests.
2. Amendments to the README, including the line for the upcoming release notes, and this should probably be for 2.5.0 not 2.4.1, @rbuisson?
3. Possible addition of an ad-hoc README for this new domain, others to weigh in as to this is overkill or not.

2022-11-21 17:34 UTC, ibacher commented
> Possible addition of an ad-hoc README for this new domain, others to weigh in as to this is overkill or not.

I actually think documenting this domain is crucial.

2022-11-24 17:58 UTC, icrc-jofrancisco commented
Hi @ibacher @rbuisson @mks-d,
I added some tests, changed some names and completed the readme files.
I'm open to new suggestions or changes that might be needed.

Thanks,

2022-11-29 07:51 UTC, mks-d reviewed
@icrc-jofrancisco did you see that the GitHub Actions build is failing? Could you have a look?

2022-11-30 11:10 UTC, rbuisson commented
@ibacher , didn't you mention that the AMPATH forms translation files should be attached to forms via a form resource?

2022-12-14 12:52 UTC, rbuisson commented on readme/ampathformstranslations.md
> +}
Do we really need that even when using the form resource?
I was under the impression that saving the translations as form resources would avoid having to specify the said translation file UUID in the form.

2022-12-14 17:55 UTC, Ruhanga commented on readme/ampathformstranslations.md
> +}
Correct @rbuisson. Specifying this form translation uuid is not a requirement. To make this non umbigious, let me remove it.

2022-12-15 17:57 UTC, ibacher reviewed
Thanks @Ruhanga! Functionality-wise, this looks great, just a few comments on polishing this up.

2022-12-15 17:57 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java
> +		String jsonTranlsationsFileName = FilenameUtils.removeExtension(file.getName());
Do we need this line? The naming convention is for the file-as-stored... I don't necessarily want to impose a naming convention on the file in the configuration folder.

2022-12-15 17:57 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java
> +			        "'language' property is required for AMPATH forms translations loader and should align with locale appended to the file name.");
```suggestion
			        "'language' property is required for AMPATH forms translations loader");
```

2022-12-15 17:57 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java
> +				throw new IllegalArgumentException("No AMPATH form exists for AMPATH form tranlsations file: "
I think we need two checks here:

1. Does the form property exist and have a value
2. Does a form of that name exist

The message here should probably be:

```suggestion
				throw new IllegalArgumentException("Could not find a form named '" + formName + "'. Please ensure a form of this name exists in your configuration.");
```

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +    public ExpectedException thrown = ExpectedException.none();
Can you make the indentation here consistent (tabs v spaces)

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +		// Verify clob
```suggestion
		// Verify
```

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +		FormResource formResource = formService.getFormResourceByUuid(RESOURCE_UUID);
This belongs in the Verify section, I think.

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +		Assert.assertEquals("\"c5bf3efe-3798-4052-8dcb-09aacfcbabdc\"", actualObj.get("uuid").toString());
Wouldn't it be simpler to just compare the string values and use the `textValue()` on the JsonNode?

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +		// Verify clob
```suggestion
		// Verify
```

2022-12-15 17:57 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java
> +		String test_file_updated = "src/test/resources/testdata/testAmpathformstranslations/test_form_updated_translations_fr.json";
Should have a comment here, e.g. `// Now load updated values`

2022-12-15 17:57 UTC, ibacher commented on api/src/test/resources/testAppDataDir/configuration/ampathformstranslations/test_form_translations_fr.json
> +}
```suggestion
}

```

2022-12-15 17:57 UTC, ibacher commented on readme/ampathforms.md
> +**NOTE:** The [AMPATH Form Builder](https://openmrs-spa.org/formbuilder/) does not include by default a reference to the encounter type. For encounter-based forms, it is important to specify an `"enc
I think the original placement of "by default" actually reads better.

```suggestion
**NOTE:** The [AMPATH Form Builder](https://openmrs-spa.org/formbuilder/) does not include a reference to the encounter type by default. For encounter-based forms, it is important to specify an `"encounter"` field with the name of the encounter type associated with the form, or else Initializer will not be able to properly load the form.
```

2022-12-15 17:57 UTC, ibacher commented on readme/ampathformstranslations.md
> +* The `form` attribute must be provided with an existing form name for the translations to load successfully. The translations form resources get names following the following pattern `<form_name>_tr
I'd use `<language>` in place of `<locale>` or rename the property to `locale`.

2022-12-16 17:17 UTC, ibacher approved these changes

2022-12-16 17:17 UTC, ibacher commented
Code looks good... Not sure about the build failure...

2022-12-21 08:33 UTC, Ruhanga reviewed
The fails randomly on with github actions but passes locally @ibacher.

2022-12-21 11:48 UTC, rbuisson commented
GitHub Actions seems to be failing to get the `org.bahmni.module:bahmnicore-api:jar:0.93-1.1.0` dependency. If removing this dependency from your local Maven repo, you should face the same issue.

2022-12-21 11:55 UTC, rbuisson commented
Adding this to pom.xml `<repositories>` section shall fix it.
```
        <repository>
            <id>mks-repo</id>
            <name>Mekom Solutions Nexus</name>
            <url>https://nexus.mekomsolutions.net/repository/maven-public</url>
        </repository>
```

2022-12-21 16:58 UTC, merged