[#212] Message Source should interpret messages.properties with no su…
mekomsolutions/openmrs-module-initializer pull request #213
Opened 2022-12-16 22:08 UTC by mogoodrich

…ffix as Englis

2022-12-16 22:42 UTC, mogoodrich commented
Closing this, this needs to be tweaked/fixed

2022-12-16 22:42 UTC, mseaton approved these changes

2022-12-16 23:36 UTC, mogoodrich commented
My original PR preferred English over the default locale set via OpenMRS global property (and caused a test failure).  New PR with what is hopefully the proper fix and a new test.

2022-12-17 02:26 UTC, mseaton requested changes
One minor comment to remove a bad import.  Also should add a bullet point to the release notes describing the change.

2022-12-17 02:26 UTC, mseaton commented on api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceIntegrationTest.java
> +import net.sf.cglib.core.Local;
Bad import - remove this

2022-12-19 15:04 UTC, mogoodrich commented
FYI, looks like the build error is unrelated to this commit? "Error:  Failed to execute goal on project initializer-api-bahmni: Could not resolve dependencies for project org.openmrs.module:initializer-api-bahmni:jar:2.4.1-SNAPSHOT: The following artifacts could not be resolved: org.bahmni.module:bahmnicore-api:jar:0.93-1.1.0, org.openmrs.module:episodes-api:jar:1.0-1.0.0: Could not find artifact org.bahmni.module:bahmnicore-api:jar:0.93-1.1.0 in openmrs-repo (https://mavenrepo.openmrs.org/public) -> [Help 1]"

2022-12-20 17:21 UTC, mogoodrich commented
This should be ready to go now @mks-d @mseaton @ibacher

2022-12-20 20:19 UTC, mseaton approved these changes
Looks good to me.  @ibacher / @mks-d - happy to provide some context on this.  Would be good to get this bug fix merged in sooner rather than later.

2022-12-20 20:33 UTC, mogoodrich commented
Thanks @mseaton ... yes @ibacher @mks-d  it's a rather serious bug... ironically, it means that if your OS locale is something other than English, when people set their OpenMRS locale to that language, the site generally shows up in English instead.

2022-12-21 09:15 UTC, mks-d approved these changes

2022-12-21 09:16 UTC, merged