Issue-209: Fixing validator
mekomsolutions/openmrs-module-initializer pull request #217
Opened 2023-02-08 14:23 UTC by Ruhanga

Issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/209

2023-02-08 14:34 UTC, ibacher commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_4.java
> -@Component
Isn't this going to break things in the Activator itself? There we depend on this being registered in the Spring Context ([here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/41a275cc75040c23de34ab7537628b2d5e232708/api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java#L49)).

2023-02-08 14:38 UTC, ibacher commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
It might be better to use MariaDB...

2023-02-16 05:32 UTC, Ruhanga commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
The MariaDB containers need some extra steps of configuration unlike running the standard MySQL containers out of the box seamlessly - which is as good for loading and validating metadata especially where not in production.

2023-02-16 08:40 UTC, mks-d commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
@Ruhanga I had to choose MariaDB over MySQL because it just wasn't possible to load the CIEL SQL file otherwise. So if that's ok now with MySQL, then ok. Could you confirm?

2023-02-16 11:41 UTC, Ruhanga commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
Works fine with MySQL.

2023-02-16 11:53 UTC, mks-d commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
Did you test it and it loads fine?

2023-02-16 17:27 UTC, Ruhanga commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
Yes @mks-d.

2023-02-17 08:10 UTC, mks-d reviewed
Looks good to me, set aside a minor comment. Then I think this could be undrafted and reviewed fully by @ibacher.

2023-02-17 08:10 UTC, mks-d commented on validator/src/main/java/org/openmrs/module/initializer/validator/Validator.java
> +		}
This block probably needs to be reworked.

2023-02-17 14:35 UTC, mks-d commented on validator/pom.xml
> +    <openmrsPlatformVersion>2.3.3</openmrsPlatformVersion>
Why not take the highest possible 2.3.x available then, like 2.3.5?

2023-02-17 14:35 UTC, mks-d commented on validator/pom.xml
> +      <version>5.1.45</version>
That's a big downgrade, what's up here?

2023-02-17 15:05 UTC, ibacher commented on validator/src/main/java/org/openmrs/module/initializer/validator/Validator.java
> +		inizLogger.setLevel(org.apache.log4j.Level.WARN); // this is to focus the Inititalizer log file to the most relevant messages
Might be good to have this set to `INFO` for the validator?

2023-02-17 15:07 UTC, Ruhanga commented on validator/pom.xml
> +      <version>5.1.45</version>
For some reason the liquibase framework is not smoothly compatible with the 8.0.16 MySQL connector. So opting for the one that's similar to what comes with OpenMRS Core 2.3.x.

2023-02-20 09:30 UTC, mks-d commented on validator/pom.xml
> +    <openmrsPlatformVersion>2.3.3</openmrsPlatformVersion>
Did you see this one ↑?

2023-02-20 09:30 UTC, mks-d commented on validator/pom.xml
> +      <version>5.1.45</version>
@Ruhanga but why was this working before? Is it a case of MariaDB vs MySQL? Because it doesn't sound good to downgrade something that much (3 major versions!).

2023-02-21 08:28 UTC, Ruhanga commented on validator/pom.xml
> +      <version>5.1.45</version>
It's a case of liquibase vs the MySQL connector. It was also failing with MariaDB and the liquibase changesets could not run altogether.

2023-02-21 08:30 UTC, Ruhanga commented on validator/pom.xml
> +    <openmrsPlatformVersion>2.3.3</openmrsPlatformVersion>
Yes @mks-d, thanks. I'll upgrade to 2.3.5.

2023-02-21 08:58 UTC, Ruhanga commented on validator/src/main/java/org/openmrs/module/initializer/validator/Validator.java
> +		inizLogger.setLevel(org.apache.log4j.Level.WARN); // this is to focus the Inititalizer log file to the most relevant messages
Ok.

2023-02-27 10:25 UTC, mks-d commented on readme/validator.md
> +3) Run it (use absolute paths for arguments and replace `<initializer_validator_version>` with the actual initializer version being used starting from version 2.5.0):
Let's put the current version at a given time so that when someone reads the docs they can just copy/paste. The version will be searched & replaced through the release process as new extra step just for that validator.md file.

2023-02-27 14:02 UTC, ibacher commented on validator/pom.xml
> +      <scope>compile</scope>
Shouldn't this be `runtime` like with the other modules?

2023-02-27 14:20 UTC, ibacher commented on validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
> +	private static MySQLContainer mysqlContainer = new MySQLContainer("mysql:5.7.31");
@Ruhanga Did you actually test _this current configuration_? Because, for me, this doesn't work out of the box. The problem seems to be that we're using a very old MySQL connector, but a version of MySQL with newer SSL ciphers. I think that for this to work, we need to explicitly disable SSL (or move to an older MySQL version).

When I run this, I get the warning:

"Mon Feb 27 08:50:23 EST 2023 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification."

And if I debug, the tests fail running the Liquibase changes because of a SSL error.

2023-02-28 13:02 UTC, Ruhanga commented on validator/pom.xml
> +      <scope>compile</scope>
Yes @ibacher, nice catch thanks.

2023-02-28 13:05 UTC, Ruhanga commented
Yes I did test this configuration on on a Mac env and didn't come across the error. I can disable SSL as default.

2023-02-28 13:17 UTC, ibacher commented
@Ruhanga Yeah, it's a general error we've had before with older versions of OpenMRS-Core and (somewhat) newer versions of MySQL. I was also testing this on a Mac... Don't know why we'd see different results, though...

2023-02-28 15:22 UTC, ibacher approved these changes
Alright, this LGTM now. Thanks @Ruhanga!

2023-02-28 16:43 UTC, ibacher commented
Actually, it looks like there's some possibility of carry-over with the validator that I don't see with Iniz itself. For example, running this against the RefApp configuration, there's an error with several drugs in the drugs domain, since they refer to concepts that aren't actually loaded. This is expected. However, the next domain to be processed (`orderfrequencies`) fails like this:

```
INFO - BaseInputStreamLoader.load(37) |2023-02-28 10:21:06,504| Loading file /Users/ibacher/<omitted>/openmrs-distro-referenceapplication/distro/configuration/orderfrequencies/orderfrequencies.csv
INFO - BaseCsvLoader.load(97) |2023-02-28 10:21:06,504| Attempting to process 9 CSV lines that have not been processed yet...
ERROR - BaseCsvLoader.lambda$load$0(117) |2023-02-28 10:21:06,507| An OpenMRS object could not be constructed or saved from the following CSV line:
+--------------------------------------+-------------+-------------------+-------------------+------------+-------------+
| Uuid                                 | Void/Retire | Frequency per day | Concept frequency | _version:1 | _order:7000 |
+--------------------------------------+-------------+-------------------+-------------------+------------+-------------+
| 136ebdb7-e989-47cf-8ec2-4e8b2ffe0ab3 |             |                 1 |        Once daily |            |             |
+--------------------------------------+-------------+-------------------+-------------------+------------+-------------+
org.hibernate.PropertyValueException: not-null property references a null or transient value : org.openmrs.Drug.concept
	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:106)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.scheduleUpdate(DefaultFlushEntityEventListener.java:309)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:160)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:231)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:102)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:61)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1227)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1293)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at org.hibernate.internal.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:966)
	at org.openmrs.api.db.hibernate.HibernateOrderDAO.getOrderFrequencyByUuid(HibernateOrderDAO.java:524)
	at org.openmrs.api.impl.OrderServiceImpl.getOrderFrequencyByUuid(OrderServiceImpl.java:726)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy122.getOrderFrequencyByUuid(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:303)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.openmrs.aop.LoggingAdvice.invoke(LoggingAdvice.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy138.getOrderFrequencyByUuid(Unknown Source)
	at org.openmrs.module.initializer.api.freq.OrderFrequenciesCsvParser.bootstrap(OrderFrequenciesCsvParser.java:36)
	at org.openmrs.module.initializer.api.freq.OrderFrequenciesCsvParser.bootstrap(OrderFrequenciesCsvParser.java:14)
	at org.openmrs.module.initializer.api.display.DisplaysCsvParser.bootstrap(DisplaysCsvParser.java:34)
	at org.openmrs.module.initializer.api.CsvParser.initialize(CsvParser.java:227)
	at org.openmrs.module.initializer.api.CsvParser.process(CsvParser.java:198)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.load(BaseCsvLoader.java:99)
	at org.openmrs.module.initializer.api.loaders.BaseInputStreamLoader.load(BaseInputStreamLoader.java:40)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.preload(BaseCsvLoader.java:72)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.preload(BaseFileLoader.java:51)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.lambda$loadUnsafe$1(BaseFileLoader.java:82)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.loadUnsafe(BaseFileLoader.java:83)
	at org.openmrs.module.initializer.api.InitializerServiceImpl.loadUnsafe(InitializerServiceImpl.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.s [...]

2023-03-01 13:13 UTC, Ruhanga reviewed
Thanks for the review @ibacher. This behaviour somewhat validates the need for a validator. For example the `3.0.0-beta.2` Ref App Distro configuration only has 20 drugs failing to load where as the current SNAPSHOT has 327 drugs failing to load. IMO it could be there are some inconsistent changes being mistakenly added to the configuration.

2023-03-01 13:53 UTC, ibacher commented
Absolutely! And, as soon as we get this working, I intend to have the validator running against any metadata PRs, so we can catch these things...

However, the problem above is that in the Validator, but not in Iniz itself, if the drugs domain fails to load, all domains after the drugs domain also fail to load, so we're not usefully validating all of the domains...

2023-03-02 10:36 UTC, mks-d requested changes
@ibacher the decision is to fix the unsafe mode in order to consider this PR complete. @Ruhanga to continue with this through subsequent commits.

2023-03-02 14:00 UTC, ibacher commented
Ok. In that case, I'm happy to merge this in. It's absolutely progress from where we were.

2023-03-03 12:10 UTC, mks-d approved these changes

2023-03-03 13:20 UTC, merged