[#211]: Demonstrating bug in test
mekomsolutions/openmrs-module-initializer pull request #218
Opened 2023-02-17 14:52 UTC by Ruhanga

Issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/211

2023-02-22 21:05 UTC, mseaton requested changes
This isn't exactly what I had in mind @Ruhanga .  See the comment / request I made on the ticket here:  https://github.com/mekomsolutions/openmrs-module-initializer/issues/211#issuecomment-1332595549.

We should implement this service method to do - as efficiently and correctly as possible - that which we need it to do, which is to retrieve a concept uniquely by FSN without regard for Locale.  So we should just do that in the DAO directly.

Beyond this, it feels a bit limiting to me for us to create such a specific service for just one method.  Since the need for specific DAO methods and services is relatively rare, it would be nice to just have an InitializerService...Impl...DAO...HibernateDAO, that could contain an assortment of service methods and DAO implementations as needed by the various domains in the module, rather than have these limited within the Concept domain.  If, one day, we find we need to add an improved service method for some other domain, it would be nice not to have to write another 4 classes and wire them all up to the Context and such.  I'd rather just write a new method in the existing (generic) classes.

We can debate the last point (not sure if @mks-d or @rbuisson have different perspectives), but I'd like to improve the DAO method as I described in the ticket unless we made the decision not to do so deliberately.

2023-02-24 07:13 UTC, Ruhanga reviewed
Thanks @mseaton for the review. I agree with the suggestions. I have one minor question, is it possible that two concepts in different locales at one time can have deferent meanings for the same literal name/word in which case we'd have to decide which concept is required? Could this be a real world scenario that we'd need to address here or how would you suggest we handle such a case?

2023-02-24 12:48 UTC, mseaton commented
@Ruhanga - I'd suggest in this case we just fail hard - throw an exception indicating that the given Concept row cannot be loaded because the concept name matches the FSN of more than one concept.  If a name is ambiguous in terms of which Concept it represents, then it should not be used/allowed as a valid identifier.

2023-02-27 14:08 UTC, mseaton requested changes
Hi @Ruhanga .  Looking better.  A few changes requested.  See comments.

2023-02-27 14:08 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +	@Autowired
See above, don't autowire this in, but wire it into the existing service bean definition in the moduleApplicationContext.xml file.

2023-02-27 14:08 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +	public Concept getConceptByName(String name) {
Javadoc

2023-02-27 14:08 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
>  		try {
This entire try/finally block along with the line above should be removed and replaced with a call to "service.getConceptByName(id)" only.  There is no longer any need to iterate over Locales and to set/reset the context locale.  So all this should be removed.

2023-02-27 14:08 UTC, mseaton commented on api/src/test/java/org/openmrs/module/initializer/api/ConceptsLoaderIntegrationTest.java
> +		Context.setLocale(localeEn);
Setting the context locale here should no longer be needed for this test.  Remove this to eliminate confusion.

2023-02-27 14:08 UTC, mseaton commented on api/src/test/java/org/openmrs/module/initializer/api/ConceptsLoaderIntegrationTest.java
> +	}
Please make sure that the existing unit tests cover the different cases that your service now handles.  eg. You should make sure there are tests that things will fail if 2 concepts have the same FSN in different locales.  You should make sure that a row will be found by FSN regardless of locale (eg. if the name locale is different from the current Context locale).

2023-02-27 14:40 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		criteria.add(Restrictions.eq("concept.retired", false));
@mseaton Semantically, I'm not sure it makes sense to unretire a concept by FSN. The FSN, AFAICT, is only guaranteed to be unique for unretired concepts, so for a retired concept, a FSN is no longer a unique concept identifier (I mean, theoretically, it would work if there's only the one retired concept with a FSN, but I imagine most times you're retiring a concept like that, it's to replace it with a different concept with the same FSN).

2023-02-27 14:41 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +	public Concept getConceptByName(String name) {
Shouldn't we take some account of locale here? It's completely possible for a concept to have the same FSN in both English and French, for example...

2023-02-27 14:45 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			throw new RuntimeException("Multiple concepts with the same fully specified name found for '" + name + "'");
While these kinds of errors are probably OK in the API, in Iniz, this is actually a user-facing error message (since this error will be logged for the user and they'll have to figure out what is wrong), in which case, it would be nice to have some way of identifying _which_ concepts share a FSN so they can be fixed. This could be as simple as:

```suggestion
			throw new RuntimeException("Multiple concepts with the same fully specified name found for '" + name + "':\n" + list.stream().map(Concept::getUuid).collect(joining("\n")));
```

2023-02-27 15:01 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +	public Concept getConceptByName(String name) {
No, the whole point is that we want this to be independent of Locale.  The use case is for uniquely identifying Concepts.  If more than one concept has the same FSN, then the name shouldn't be used as an identifier.   But actually, what we probably want to do is to have the DAO return a List<Concept> of all concepts that match the FSN (independent of Locale).  Then, the service should make the judgement around what to do with this List depending on the size of members returned (which is to fail on duplicate and return null on empty).  Make sense @Ruhanga

2023-02-27 15:03 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +	public Concept getConceptByName(String name) {
We should also probably change this method name.  It isn't descriptive enough for what it is actually doing.  It should read something like "getUnretiredConceptByFullySpecifiedName" or "getUniqueConceptByFullySpecifiedName" or something.

2023-02-28 08:35 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +	public Concept getConceptByName(String name) {
Makes sense @mseaton. Will implement the [agreed on logic below](https://github.com/mekomsolutions/openmrs-module-initializer/pull/218#discussion_r1118869129).

2023-02-28 10:24 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/ConceptsLoaderIntegrationTest.java
> +		Context.setLocale(localeEn);
Ok..

2023-02-28 10:25 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
>  		try {
Resolved.

2023-02-28 10:25 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +	public Concept getConceptByName(String name) {
Ok..

2023-02-28 10:25 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +	@Autowired
Done...

2023-02-28 10:25 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		criteria.add(Restrictions.eq("concept.retired", false));
Ok..

2023-02-28 10:26 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +	public Concept getConceptByName(String name) {
Javadoc added.

2023-02-28 10:26 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +	private SessionFactory sessionFactory;
Done..

2023-02-28 10:26 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +public class HibernateInitializerDAO implements InitializerDAO {
Done...

2023-02-28 10:27 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> + * The Hibernate class for Concepts <br>
Corrected, thanks for the review @mseaton.

2023-03-01 12:24 UTC, mseaton requested changes

2023-03-01 12:24 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		return null;
So, what about the situation where a single concept has the same FSN in multiple languages?  For example, we might have the FSN "Tumor" in both English and Spanish.  In this case, we would not want this method to fail, since "Tumor" would refer to a single Concept.  Right, @Ruhanga  / @ibacher ?

Per my comment above, I think this DAO method should retrieve the distinct Concept projections that match the criteria query and return that List/Set of distinct matching Concepts.

So this method would return Set<Concept> (or  List<Concept> where we make sure there are no duplicates in the List)

2023-03-01 12:24 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		if (StringUtils.isBlank(name)) {
Thinking this over, I think this DAO method would be more useful returning a List<Concept> or Set<Concept> and be named "getUnretiredConceptsByFullySpecifiedName(String name)", and then the consumer (either the service method or the consumer of that) would contain the logic to check whether there is 0, 1, or >1 result, and throw and exception if > 1.  That seems more appropriate to API logic, not DAO query logic.

2023-03-01 12:24 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +		return initializerDAO.getUnretiredConceptByFullySpecifiedName(name);
Per my comment above, if a valid scenario exists where an FSN could be shared by multiple concepts, then this method should return a Set or List of those Concepts, and it should be down to the consuming class to figure out whether it can handle multiple concepts or not.

2023-03-01 12:24 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
> +		Concept concept = Context.getService(InitializerService.class).getUnretiredConceptByFullySpecifiedName(id);
If the service and DAO methods change above to return a List<Concept>, _this_ is the appropriate place to check if the size of the returned List is 0 (return null), 1 (return the first member), or > 1 (throw an Exception that lists the offending concepts).

2023-03-01 13:49 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		return null;
While I'm not opposed to returning a list or set from this method, to address the "Tumor / Tumor" thing, we just need to change the query so that its fetching concepts (instead of concept names) and do a unique projection... We'd still end up with a single concept.

The value to returning multiple concepts is if we expect more than one _concept_ to have the same FSN, but in different locales...

2023-03-01 14:29 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		return null;
Correct @ibacher - there are 2 separate things here.  Either way, we need to fix this method so that it is returning distinct projections of Concept, not just counting concept names.  *Then*, we need to decide separately if we want the logic as to whether to return one concept or a list, and where to throw exceptions to be in the DAO, service, or consumers of the service.

2023-03-03 13:29 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
> +		Concept concept = Context.getService(InitializerService.class).getUnretiredConceptByFullySpecifiedName(id);
I've added this change.

2023-03-03 13:30 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
> +		return initializerDAO.getUnretiredConceptByFullySpecifiedName(name);
Method now returns List of Concepts.

2023-03-03 13:30 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		if (StringUtils.isBlank(name)) {
Method now returns List of Concepts.

2023-03-03 13:31 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +		return null;
I've added projection on distinct concepts.

2023-03-03 13:33 UTC, Ruhanga reviewed
Hi @ibacher, @mseaton, thanks for your reviews. I've addressed most of the requested changes. Could you have a look again? Thanks.

2023-03-03 13:46 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
One quick thing @Ruhanga  - I wonder if we can reduce the level of this warning.  Where this method is typically used, we are in a situation where we have a lookup string and are attempting to match on uuid, mapping, name, etc.  So the fact that no matching name is found when this method is called is not necessarily a warning-level event, and can cause unnecessary concern when looking at logs.  Thoughts?

2023-03-03 13:47 UTC, mseaton commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerService.java
> +	 * Return a Concept that matches the exact fully specified name
Minor comment that javadoc now needs to change to reflect return of multiple concepts

2023-03-03 13:48 UTC, mseaton approved these changes
Couple of quick things to fix but otherwise looks great.  Approving on my end.

2023-03-05 07:44 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
The warning-level IMO is fairly ok to maintain [from the previous implementation in core](https://github.com/openmrs/openmrs-core/blob/2.1.x/api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java#L1739) since it'd ideally help identify a concept that'd be getting newly created and/or missing for any other domain requiring it via this method. This can be quite handy unlike having to go through a more detailed debug log that can be quite verbose to clearly zero-down to the cause.

2023-03-06 14:18 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
At the very least, this logging seems unnecessary here if we're also doing it in the Utils method no? I think we can leave out the logging here and allow the level above to log something... As written, this logs two warnings if the concept isn't found which seems like a lot.

2023-03-06 14:18 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
I also would tend to prefer this at the `info` level rather than `warn`.

2023-03-06 14:19 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
> +			return concepts.iterator().next();
```suggestion
			return concepts.get(0);
```

2023-03-06 14:23 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
We've done away with the one in the DAO method @ibacher.

2023-03-06 14:23 UTC, ibacher commented on api/src/main/resources/moduleApplicationContext.xml
> +            	<property name="initializerDAO">
Minor, but could we consistently use spaces in this XML file?

2023-03-06 14:24 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/InitializerService.java
> +	 * Returns Unretired unique Concepts that match the exact fully specified name across all locales
```suggestion
	 * Returns non-retired unique concepts whose fully specified name exactly matches the supplied name in any locale
```

2023-03-06 14:26 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
This comment is on the DAO method, right? Because I still see it in this PR...

2023-03-06 14:28 UTC, Ruhanga commented on api/src/main/resources/moduleApplicationContext.xml
> +            	<property name="initializerDAO">
Yes @ibacher, thanks.

2023-03-06 14:39 UTC, ibacher approved these changes

2023-03-06 14:49 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/HibernateInitializerDAO.java
> +			log.warn("No concept found for '" + name + "'");
In the case that everything is running okay, it is ok to hide such logs unlike when something failed. I'd keep the logs maybe at INFO level like suggested.

2023-03-06 15:19 UTC, merged