[#211] Undo InitializerDAO xml injection in favour of Autowire injection
mekomsolutions/openmrs-module-initializer pull request #228
Opened 2023-03-13 07:31 UTC by Ruhanga

This is a followup PR to address a runtime bug caused by the InitializerDAO not being set.
Issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/211

2023-03-13 07:54 UTC, mks-d approved these changes
If this solves a bug at runtime, then it's good to go for me.

2023-03-13 09:03 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/module/initializer/api/DrugsLoaderWithMappingsIntegrationTest.java
> +		// to prevent Data Filter's 'Illegal Record Access'
@Ruhanga do you know why Data Filter interferes with this new domain?

2023-03-13 10:19 UTC, mks-d requested changes

2023-03-13 10:19 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/module/initializer/api/DrugsLoaderWithMappingsIntegrationTest.java
> +		// to prevent Data Filter's 'Illegal Record Access'
Looks like all api-2.3 (and beyond) Spring tests will need this because Data Filter becomes a dependency from 2.3, so let's make sure that this becomes the default behaviour for all tests in api-2.3.

Let's make it its own PR.

2023-03-13 11:04 UTC, Ruhanga commented on api-2.3/src/test/java/org/openmrs/module/initializer/api/DrugsLoaderWithMappingsIntegrationTest.java
> +		// to prevent Data Filter's 'Illegal Record Access'
PR [here](https://github.com/mekomsolutions/openmrs-module-initializer/pull/229) @mks-d.

2023-03-13 11:13 UTC, mks-d approved these changes

2023-03-13 11:13 UTC, merged

2023-03-13 11:45 UTC, mseaton commented
@Ruhanga / @mks-d .  This was already merged, so not sure you need or want my review still.  No reason to oppose this, as long as it works and doesn't lead to performance issues, particularly at startup.  I _would_ like to know why this is necessary though - do we know what kind of situation works when we inject dependencies via autowiring and does not work when we explicitly inject using xml mappings?  Seems odd.

2023-03-14 14:03 UTC, mogoodrich commented
@Ruhanga  @mks-d  I confirmed that this change (Autowired in a service) literally added 4 minutes to the start up time of our PIH EMR dev environments (haven't checked production instances but I assume the same as well). 

This is due to this pesky issue that we've never figured out how to solve besides not autowiring in bean.

https://issues.openmrs.org/browse/TRUNK-3806

This is a blocker for our development, can we revert this until we figure it out, or at least revert and do a release before adding, because we need @mseaton 's drug CSV enhancement that only in this snapshot.  Thanks!