[#252]: Support explicit addresshierarchy domain.
mekomsolutions/openmrs-module-initializer pull request #254
Opened 2023-10-31 19:52 UTC by Ruhanga

#252

2023-11-01 06:18 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AddressHierarchyLoader.java
> +			Context.getService(AddressHierarchyService.class).initI18nCache();
@mogoodrich this is always gona initialize the i18n cache at startup from here. `initializeFullAddressCache()` is implicitly called by `AddressConfigurationLoader.loadAddressConfiguration(...)`

2023-11-01 06:27 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AddressHierarchyLoader.java
> +			Context.getService(AddressHierarchyService.class).initI18nCache();
I've also tweaked this to ensure the `initializeFullAddressCache` is always called not only when checksums are changed.

2023-11-01 11:05 UTC, mseaton requested changes

2023-11-01 12:36 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AddressHierarchyLoader.java
> +			Context.getService(AddressHierarchyService.class).initI18nCache();
Yes, @mseaton  that is my preference as well, that Iniz sticks to loading metadata, and *not* being responsible for setting up in-memory caches.  

I believe the original loadAddressConfiguration method already did #1: reloads the cache if the AH entries are reloaded.  #2 could be added as well, but is not really necessary if the if we keep the method that refreshes the cache in the contextRefreshed method of the Address Hierarchy activator.

@Ruhanga  @mks-d  I assume the intent of Iniz is primarily to do metadata loading, not to do overall module start-up tasks?  For instance, if for some reason Iniz was uninstalled from an implementation, I'd still expect a module to start up properly, as long as it's metadata was already loaded?

2023-11-01 13:37 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AddressHierarchyLoader.java
> +			Context.getService(AddressHierarchyService.class).initI18nCache();
> I assume the intent of Iniz is primarily to do metadata loading, not to do overall module start-up tasks?

Yes, I think that's explicitly the purpose here.

2023-11-01 13:40 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	ADDRESS_HIERARCHY,
Should the address hierarchy be loaded before locations?

2023-11-01 13:40 UTC, ibacher commented on api/src/test/java/org/openmrs/module/initializer/api/AddressHierarchyLoaderIntegrationTest.java
> +		    new GlobalProperty(OpenmrsConstants.GLOBAL_PROPERTY_LOCALE_ALLOWED_LIST, "en_GB, km_KH"));
Is there a reason that this switched from `en` to `en_GB`? Does `en` not work? (Most locales in OpenMRS are stored as language without country specifier).

2023-11-01 19:20 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	ADDRESS_HIERARCHY,
Address hierarchy and OpenMRS Location are different and/or disjoint entities, but sounds logical to load the `ADDRESS_HIERARCHY` domain after the `LOCATIONS` domain.

2023-11-01 19:25 UTC, Ruhanga commented on api/src/test/java/org/openmrs/module/initializer/api/AddressHierarchyLoaderIntegrationTest.java
> +		    new GlobalProperty(OpenmrsConstants.GLOBAL_PROPERTY_LOCALE_ALLOWED_LIST, "en_GB, km_KH"));
I was trying to add `km_KH` to the list, but looks like in tests too, `en_GB` is the [default locale](https://github.com/openmrs/openmrs-core/blob/c6de9235691e83dde50c047be9b2168eac1faf3b/api/src/main/java/org/openmrs/util/OpenmrsConstants.java#L328C29-L328C73) which constrains me to use it instead when populating the locale allowed list.

2023-11-02 06:32 UTC, Ruhanga commented on api/src/main/java/org/openmrs/module/initializer/api/loaders/AddressHierarchyLoader.java
> +			Context.getService(AddressHierarchyService.class).initI18nCache();
>For instance, if for some reason Iniz was uninstalled from an implementation, I'd still expect a module to start up properly, as long as it's metadata was already loaded?

This would cause some malfunctioning already(as is the case) since Iniz does load the i18n message properties necessary for proper cache initialization from the now proxy `addresshierarchy` domain.

2023-11-02 13:20 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	ADDRESS_HIERARCHY,
Agree, I don't think it makes much of a different (yet?), but loading locations makes the most sense to me.

2023-11-07 08:24 UTC, mks-d requested changes

2023-11-07 08:24 UTC, mks-d commented on readme/addresshierarchy.md
> +* The i18n `.properties` files are used to populate the address/location i18n cache. The messages files can be similarly defined as those loaded by the [messageproperties](readme/messageproperties.md
I'm assuming this is optional, correct? So this is not just for Ext I18n reverse cache? Could you expand further, I don't think it's clear to the reader what this is about and how it should be used.

2023-11-08 10:42 UTC, mks-d approved these changes

2023-11-08 10:43 UTC, merged