O3-2446: load queue.status_concept_set field
mekomsolutions/openmrs-module-initializer pull request #260
Opened 2024-01-16 20:20 UTC by cioan

@mseaton , I just added the ability to load the new queue.status_concept_set field that you added as part of the O3-2446 ticket. Thanks!

2024-01-16 21:30 UTC, mseaton commented
@cioan - the issue is that this will likely fail for anyone not running the latest snapshot of queue.  It assumes that anyone loading in from the queue domain is running the latest version of the module, which is likely not true.

2024-01-17 15:42 UTC, cioan commented
Thanks @mseaton ! I just updated the dependencies to depend on the released version of the queue module.

2024-01-17 19:21 UTC, ibacher commented
> I don't see any clear existing examples of this at first glance.

I think we've been trying not to have the endless series of configurations for various versions of things. If we wanted that though, it would be possible to do two LineProcessors like this:

```java
@OpenmrsProfile(modules = { "queue:* - 1.*" })
```

```java
@OpenmrsProfile(modules = { "queue:2.*" })
```

2024-01-18 03:14 UTC, mseaton requested changes
See my comments in the PR @cioan .  A few other things:
* You will need to update the README as part of this PR to reflect these additions.  Make sure you indicate that these are supported for Queue version 2.1.0 and higher.
* Will will need to update the release notes as a part of this PR.

2024-01-18 03:14 UTC, mseaton commented on api-2.3/src/main/java/org/openmrs/module/initializer/api/queues/QueueLineProcessor.java
> +	protected static String HEADER_STATUS_CONCEPT_SET = "statusConceptSet";
This does not really match the existing standard in initializer.  Have a look at some other LineProcessor classes, the headers tend to be more human readable (spaces between words, not camel case, etc).

2024-01-18 03:14 UTC, mseaton commented on api-2.3/src/main/java/org/openmrs/module/initializer/api/queues/QueueLineProcessor.java
> +			if (StringUtils.isNotBlank(statusConceptSet)) {
The key thing here is to ensure this is backwards compatible.  I _think_ this should be fine - the `setStatusConceptSet` method is not invoked unless the appropriate header is present, so for existing implementations that have an earlier version without this method and also CSV files that don't contain this header, I think this should be ok.  It would be worth verifying/testing though.

2024-01-18 03:14 UTC, mseaton commented on api-2.3/src/main/java/org/openmrs/module/initializer/api/queues/QueueLineProcessor.java
> +
Whatever code you have added to handle `statusConceptSet`, you also need to add in to handle `priorityConceptSet`, which was added to Queue at the same time.  We should cover both of these in this update.

2024-01-18 13:07 UTC, cioan commented
Thanks @mseaton ! I have addressed all your comments above. I also add @ibacher and @mks-d to the reviewers list. Thanks!

2024-01-18 15:15 UTC, mseaton commented
> I have addressed all your comments above

@cioan - please see comment above about adding to release notes and readme.  Also, I didn't see @ibacher added as a reviewer, so I added him.

2024-01-18 15:17 UTC, mseaton commented
> I think we've been trying not to have the endless series of configurations for various versions of things

In this case, I don't think we need to do anything, as the lines that hit these methods are only executed if the headers are configured for them.  Would that match your understanding @cioan and @ibacher ?

2024-01-18 15:24 UTC, ibacher commented
@mseaton Yes, I think this should work as long as the documentation is clear. @cioan We need to update [this README file](https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/queues.md#domain-queues) with the new options.

Looking at things, it looks like the queue support is only part of the 2.7.0-SNAPSHOT? In that case, it's much easier to just say that the queues domain requires version 2.1.0. This should have a very minimal effect on anyone using the existing domain, as that's likely no one currently.

2024-01-18 15:47 UTC, cioan commented
Thanks @mseaton and @ibacher ! I have updated the queues readme file. 
@mseaton , where is the release notes file that needs to be updated?

2024-01-18 16:20 UTC, ibacher commented
Usually, it's in the main README. In this case, since we haven't done a release since we've added the queue module, I think it's already covered.

2024-01-18 16:21 UTC, mseaton commented
> Usually, it's in the main README. In this case, since we haven't done a release since we've added the queue module, I think it's already covered

Agreed.  @cioan no need to update the release notes, since support for queues has actually not been in a release yet, and what we put in for 2.7.0 covers queues generally.

2024-01-18 18:10 UTC, ibacher approved these changes

2024-01-18 18:11 UTC, ibacher commented
@mseaton If you're happy with this, do you mind approving? I think this is ready to merge.

2024-01-18 18:57 UTC, mseaton approved these changes

2024-01-18 18:58 UTC, merged

2024-01-18 19:05 UTC, cioan commented
Thanks @mseaton and @ibacher !