Add Billing Domains to Iniz
mekomsolutions/openmrs-module-initializer pull request #269
Opened 2024-06-07 05:13 UTC by ODORA0

2024-06-13 08:55 UTC, mks-d reviewed
Thanks @ODORA0. Since this is not connected to [any Iniz GitHub issue](https://github.com/mekomsolutions/openmrs-module-initializer/issues), I'll ask you to provide a comprehensive description of what all this PR bring in, could you do that?

2024-06-18 13:21 UTC, mks-d requested changes
It looks overall pretty good, though I'm confused as to why the whole thing may work when certain Spring beans haven't been defined as such...

Big miss though: documentation. We'll need a dedicated README for your new domain(s) and a couple of updates in the main README, [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/e85cc3ad2da8ec8ddd1bec95c5af9cb000b195f9/README.md?plain=1#L50-L51), [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/e85cc3ad2da8ec8ddd1bec95c5af9cb000b195f9/README.md?plain=1#L130-L131), [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/e85cc3ad2da8ec8ddd1bec95c5af9cb000b195f9/README.md?plain=1#L168-L169) and [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/e85cc3ad2da8ec8ddd1bec95c5af9cb000b195f9/README.md?plain=1#L197-L198).

2024-06-18 13:21 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/BillableServicesLineProcessor.java
> +			}
All these `fetch*` methods will return `null` when nothing's found, so theoretically you should be able to do this kind of stuff everywhere no?
```java
String service = line.getString(HEADER_SERVICE);
billableService.setConcept(Utils.fetchConcept(service, conceptService));
```
I mean you don't need the `if`/`else`.

2024-06-18 13:21 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +	protected static String HEADER_SERVICE_STATUS = "Service Status";
Same same, **lower case** on the RHS.

2024-06-18 13:21 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +				paymentMode.addAttributeType("Short Name", "String", null, false);
Why are you not using the constants you just brought in? For stuff like `"Short Name"`, etc? Unless it's important here that they are **Title Case**'d of course.

2024-06-18 13:21 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServicesLoaderIntergrationTest.java
> +public abstract class BillableServicesLoaderIntergrationTest extends DomainBaseModuleContextSensitiveTest {
Shouldn't you extend `DomainBaseModuleContextSensitive_2_3_Test`? Which in turn would allow you to not override `updateSearchIndex` anymore.

2024-06-21 05:22 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/BillableServicesLineProcessor.java
> +	protected static final String HEADER_SERVICE_STATUS = "Service Status";
Done

2024-06-21 05:22 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointCsvParser.java
> +public class CashPointCsvParser extends CsvParser<CashPoint, BaseLineProcessor<CashPoint>> {
Added

2024-06-21 05:22 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointLoader.java
> +public class CashPointLoader extends BaseCsvLoader<CashPoint, CashPointCsvParser> {
Added

2024-06-21 05:22 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/BillableServicesLineProcessor.java
> +			}
Right, done

2024-06-21 05:23 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +	protected static String HEADER_SERVICE_STATUS = "Service Status";
Done

2024-06-21 05:23 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +				paymentMode.addAttributeType("Short Name", "String", null, false);
Fixed

2024-06-21 05:23 UTC, ODORA0 commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServicesLoaderIntergrationTest.java
> +public abstract class BillableServicesLoaderIntergrationTest extends DomainBaseModuleContextSensitiveTest {
Fixed

2024-06-25 09:56 UTC, mks-d requested changes
Let's make it work with Validator, this will prove that all is well.

See this as an example (with IDGen) of what's required to be done → https://github.com/mekomsolutions/openmrs-module-initializer/blob/3b5a5417521ef7135f2dd0719418f7881bd278bd/validator/pom.xml#L186-L192

Then, you should validate that you can make a dry run of a piece of billing config, see → https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/validator.md#how-to-make-a-dry-run

2024-07-01 05:38 UTC, mks-d reviewed
@Ruhanga could you check that all is well with this new domain with the Validator?

2024-07-02 12:36 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
@ODORA0 did you need to create new test concepts, why not use some from the various test datasets?

2024-07-02 12:58 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
@ODORA0 you mean you're showing that loading the CSV will modify those concepts accordingly?

2024-07-02 13:34 UTC, ODORA0 commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
@mks-d I don't follow, please explain. Which datasets did you mean earlier?

2024-07-02 13:38 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
Within OpenMRS' Spring tests you don't necessarily need to create concepts, you have access to [this](https://github.com/openmrs/openmrs-core/blob/758715f819a712b06a554a8cba91cbaf31f63267/api/src/test/resources/org/openmrs/include/standardTestDataset.xml#L50-L87) bunch if you need concepts.

You can even load and use the following extra dataset shipped with Iniz if you ever needed more: https://github.com/mekomsolutions/openmrs-module-initializer/blob/6449d0b7bd75bf1069c1ae0a3e6710c77811350d/api/src/test/resources/testdata/test-concepts.xml#L7-L22

2024-07-03 09:52 UTC, mks-d requested changes

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +		}
Is the UUID not required (like the name is)?

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +		}
Why not
```java
cashPoint.setUuid(line.getString(HEADER_UUID));
```
?
... if the UUID is not required of course.

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceCsvParserTest.java
> +	}
Starting with this one, divide all your test methods/cases as best as can following the _given-when-then_ pattern. Eg.: https://github.com/mekomsolutions/openmrs-module-initializer/blob/6449d0b7bd75bf1069c1ae0a3e6710c77811350d/api/src/test/java/org/openmrs/module/initializer/api/display/DisplaysCsvParserTest.java#L37-L48

Also the method name follows a convention, see also the example above: `bootstrap_shouldBootstrapObjectGivenUuidPresentAndObjectNotVoid`.

As in: "method being tested" + "_" + "expected outcome".

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            Assert.assertNotNull("Concept should not be null", concept);
If this concept is in the test dataset you don't need to assert this, IMO. Also you don't need to craft a special message. If somehow the test dataset is broken, then it's another story, it will be detected and fixed accordingly.

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            Assert.assertNotNull("Concept should not be null", concept);
Same here.

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        loader.load();
Precedes this with "`// replay`":
```java
// replay
loader.load();
```

2024-07-03 09:52 UTC, mks-d commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
Precedes this with "`// verify`":
```java
// verify
...
```

2024-07-04 06:29 UTC, ODORA0 commented
@Ruhanga Please review

2024-07-04 08:27 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +        }
Are you sure you can't compactify all this into just
```java
String location = line.getString(HEADER_LOCATION);
cashPoint.setLocation(Utils.fetchLocation(location, locationService));
```
?
Did you check?

2024-07-04 08:27 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +        // UUID is required
You may remove this line is in fact the UUID is **not** required.

2024-07-04 08:27 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +
You may remove this empty line.

2024-07-04 08:27 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
>  		}
Why is the UUID required for payment modes but not for cash points?

2024-07-04 08:58 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
>  		}
They are actually required, changing that for cash points

2024-07-04 09:18 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +
Removed

2024-07-04 09:19 UTC, ODORA0 commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/CashPointsLineProcessor.java
> +        }
Done

2024-07-04 16:04 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +    protected static final String HEADER_NAME = "name";
Those two are already defined in `BaseLineProcessor`, you get them for free.

2024-07-04 16:04 UTC, mks-d commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/ServicePricesLineProcessor.java
> +        processAttribute(line, HEADER_BILLABLE_SERVICE, paymentMode);
I think we don't need to document in the code which is optional and which is not, this is done in the READMEs and should be self-explanatory through the use of the throwable version or not.

So let's get rid of the comments, you didn't set them in `CashPointsLineProcessor` anyway.

2024-07-04 19:55 UTC, Ruhanga requested changes
Thank you for adding tests, @ODORA0. Moving forward, you'll add more integration tests for each of the newly introduced domain loaders. Currently, we only have one, `BillableServiceLoaderIntegrationTest`. Here are a few other specific points to address:

2024-07-04 19:55 UTC, Ruhanga commented on api-2.4/pom.xml
> +        </dependency>
@ODORA0, we should rather depend on the sub-modules' api packages than the omod web api package.

2024-07-04 20:03 UTC, Ruhanga reviewed
Thank you for adding tests, @ODORA0. Moving forward, you'll add more integration tests for each of the newly introduced domain loaders. Currently, we only have one, `BillableServiceLoaderIntegrationTest`. Here are a few other specific points to address:

2024-07-04 20:03 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            Assert.assertEquals(BillableServiceStatus.DISABLED, service.getServiceStatus());
I don't think this is actually testing the loading of the billable services csv file located at `resources/testAppDataDir/configuration/billableservices/services.csv` since what's being retrieved is what's being saved inside `setup()` above. Else you'd have to remove `setup()` altogether or use it to save billable services to be edited or voided which are valid use-cases to test.

2024-07-04 20:52 UTC, ODORA0 commented on api-2.4/pom.xml
> +        </dependency>
@Ruhanga Please advise, given the constraint that BillableServiceResource is only available in the billing-omod module and not in the billing-api module, transitioning to use billing-api will limit the direct operations we can perform on BillableService entities since these operations are currently done through the BillableServiceResource.

Also are you suggesting adding integration tests for all the other domain in this PR as well?

2024-07-05 08:46 UTC, mks-d requested changes

2024-07-05 08:46 UTC, mks-d commented on api-2.4/pom.xml
> +        </dependency>
@ODORA0 Iniz doesn't need any REST resources, it only needs the Java API of the modules it depends on. You can indeed switch to depending on the `-api` submodule and, if all your Spring tests pass, you're good.

>Also are you suggesting adding integration tests for all the other domain in this PR as well?

Yes indeed. You need to bring as a test resource a typical, real-world looking, CSV file and demonstrate through your tests that the outcome of loading each CSV file is as expected and can be asserted.

Each `*Loader` class should have its corresponding Spring test (context sensitive) class.

2024-07-08 14:40 UTC, Ruhanga requested changes
Thank you, @ODORA0, for contributing additional tests. For all loader integration tests, our goals should encompass at least three verifications: 1.) Creating entities, 2.) Modifying existing entities, and 3.) Retiring/un-retiring of existing entities via CSV lines. You can refer to this example [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/main/api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java) for guidance.

2024-07-08 14:40 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/ServicePricesLoaderIntegrationTest.java
> +        assertEquals("Cash payment mode", paymentMode.getDescription());
This doesn't validate that the csv file `configuration/billableserviceprices/ServicePrices.csv` was loaded. Validation would be fine if what's in `setup()` of this same file was removed.

2024-07-08 14:40 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/CashPointLoaderIntegrationTest.java
> +        assertEquals(location, cashPoint.getLocation());
This doesn't validate that the csv file `configuration/billableserviceprices/cashPoints.csv` was loaded. Validation would be fine if what's in `setup()` of this same file was removed.

2024-07-08 15:39 UTC, Ruhanga requested changes
@ODORA0, please remember to provide separate dedicated README documentation for each of the added domains. This should include definitions for all the domain specific fields (See [this example](https://github.com/mekomsolutions/openmrs-module-initializer/blob/main/readme/ordertypes.md)). 

Additionally, update the existing documentation as highlighted below.

2024-07-08 15:42 UTC, Ruhanga commented on README.md
> +1. [Billing (CSV files)](readme/billing.md)
Same here

2024-07-08 15:42 UTC, Ruhanga commented on README.md
> +* Added support for 'billing' domain.
Same here.

2024-07-10 05:51 UTC, Ruhanga reviewed
> For all loader integration tests, our goals should encompass at least three verifications: 1.) Creating entities, 2.) Modifying existing entities, and 3.) Retiring/un-retiring of existing entities via CSV lines. You can refer to this example [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/main/api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java) for guidance.

Thanks for the changes @ODORA0. Let's remember to address the above comment too.

2024-07-10 05:51 UTC, Ruhanga commented on README.md
> +* Added support for 'billing' domains.
This should be added to the 2.8.0 release notes as 2.7.0 was released.

2024-07-10 05:54 UTC, Ruhanga commented on README.md
> +* Added support for 'billing' domains.
```suggestion
* Added support for 'billing' (billableservices, serviceprices, cashpoints) domains.
```

2024-07-12 12:02 UTC, Ruhanga requested changes
@ODORA0 could you please push the changes without using force push for now? It complicates the review process, especially when some comments need to be properly resolved.

2024-07-16 14:07 UTC, Ruhanga requested changes
@ODORA0 overall, this looks good. Let's refine a few details below.

2024-07-16 14:07 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +        }
This should assert that `retiredService.getRetired == true`, the same is true for similar test cases on the other domains.

2024-07-17 08:21 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/CashPointLoaderIntegrationTest.java
> +    }
This is kind of change I was expecting seen on all the loader integration tests @ODORA0.
```suggestion
    public void setup() throws Exception {
        executeDataSet("testdata/test-metadata.xml");
    }

    @Test
    public void shouldCreateCashPointsFromCSV() {
         // Replay
         loader.load();
         
        // Verify creation for all CashPoints
        CashPoint cashPoint1 = iCashPointService.getByUuid("54065383-b4d4-42d2-af4d-d250a1fd2590");
        assertNotNull(cashPoint1);
        assertEquals("OPD Cash Point", cashPoint1.getName());
        assertEquals("Opd cash point for billing", cashPoint1.getDescription());

        Location location1 = locationService.getLocation("ART Clinic");
        assertNotNull(location1);
        assertEquals("ART Clinic", location1.getName());
        assertEquals(location1, cashPoint1.getLocation());

        CashPoint cashPoint2 = iCashPointService.getByUuid("c56a108f-e3c5-4881-a5e8-a796601883b9");
        assertNotNull(cashPoint2);
        assertEquals("IPD Cash Point", cashPoint2.getName());
        assertEquals("IPD cash point for billing", cashPoint2.getDescription());

        Location location2 = locationService.getLocation("Inpatient Ward");
        assertNotNull(location2);
        assertEquals("Inpatient Ward", location2.getName());
        assertEquals(location2, cashPoint2.getLocation());

        CashPoint cashPoint3 = iCashPointService.getByUuid("8e48e0be-1a31-4bd3-a54d-ace82653f8b8");
        assertNotNull(cashPoint3);
        assertEquals("MCH Cash Point", cashPoint3.getName());
        assertEquals("MCH cash point for billing", cashPoint3.getDescription());

        Location location3 = locationService.getLocation("MCH Clinic");
        assertNotNull(location3);
        assertEquals("MCH Clinic", location3.getName());
        assertEquals(location3, cashPoint3.getLocation());
    }
```

2024-07-17 12:30 UTC, Ruhanga requested changes
A few outstanding issues need to be addressed @ODORA0. Let’s try to make sure to implement proper assertions as recommended below.

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            billableItemsService.save(service);
This should be accomplished by a `.csv` line corresponding to a pre-existing record, likely saved during the `setup()` method. When `loader.load()` is called, the existing record should be updated with the relevant line from the `.csv` file. After that, you can verify that the `.csv` line was loaded correctly.

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            billableItemsService.save(service);
Same here for retiring.

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            Assert.assertEquals(BillableServiceStatus.ENABLED, unretiredService.getServiceStatus());
Same here...

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/CashPointLoaderIntegrationTest.java
> +        iCashPointService.save(cashPoint);
Same here...

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/CashPointLoaderIntegrationTest.java
> +        iCashPointService.save(retiredCashPoint);
Same here for retiring and un-retiring

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/ServicePricesLoaderIntegrationTest.java
> +        paymentModeService.save(paymentMode);
Same here...

2024-07-17 12:30 UTC, Ruhanga commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/ServicePricesLoaderIntegrationTest.java
> +        paymentModeService.save(retiredPaymentMode);
Same here for retiring and un-retiring...

2024-07-18 12:06 UTC, ODORA0 commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceLoaderIntegrationTest.java
> +            billableItemsService.save(service);
@Ruhanga Please explain this, I don't follow

2024-07-19 10:18 UTC, Ruhanga commented
@ODORA0 do the tests you added run successfully when you run `mvn clean install`?

2024-07-19 20:56 UTC, gracepotma commented
Can't wait for this to be in RefApp, I'm really really keen to add sample config for the O3 RefApp distro!!

2024-07-24 03:24 UTC, gracepotma commented
@ODORA0 can I ask, what is the plan with this PR now? E.g. are you working to address Nathan's comments above? Forgive me if this was shared elsewhere.

2024-07-24 03:35 UTC, ODORA0 commented
@gracepotma Actually they've been worked on if you notice the commit history, waiting for any more reviews.

2024-07-24 11:59 UTC, Ruhanga commented
> @ODORA0 do the tests you added run successfully when you run mvn clean install?

@ODORA0, @gracepotmam, as asked earlier above, the current integration tests are not operational. I am addressing this as part of my prioritized tasks.

2024-07-26 15:53 UTC, Ruhanga requested changes
@ODORA0, I’ve successfully set up an appropriate test environment and resolved the issues with the Billable Services Domain integration tests. Could you take it from here and proceed with the other domain tests, using the Billable Services Domain integration tests as a reference?

2024-08-01 07:45 UTC, corneliouzbett reviewed
Left few comments.
Generally LGTM. I'll @Ruhanga have a final say in this one.

2024-08-01 07:45 UTC, corneliouzbett commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/BillableServiceCsvParserTest.java
> +import static org.mockito.Mockito.*;
Avoid using wildcard imports. Check your IDE settings it is often the IDE which merges several imports into a wildcard import.

2024-08-01 07:45 UTC, corneliouzbett commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/CashPointLoaderIntegrationTest.java
> +			Assert.assertTrue(cashPoint.getRetired());
```suggestion
		assertTrue(cashPoint.getRetired());
```
Consistent with the other static imports.

2024-08-01 07:45 UTC, corneliouzbett commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/ServicePricesLoaderIntegrationTest.java
> +			Assert.assertFalse(unretiredPaymentMode.getRetired());
```suggestion
		assertFalse(unretiredPaymentMode.getRetired());
```

2024-08-01 07:45 UTC, corneliouzbett commented on api-2.4/src/test/java/org/openmrs/module/initializer/api/ServicePricesLoaderIntegrationTest.java
> +			Assert.assertTrue(paymentMode.getRetired());
```suggestion
		assertTrue(paymentMode.getRetired());
```

2024-08-08 21:17 UTC, Ruhanga approved these changes
Generally LGTM!

2024-08-12 12:59 UTC, mks-d requested changes

2024-08-12 12:59 UTC, mks-d commented on readme/billableservies.md
> +billableservice/
This should be `billableservices/` (plural), hopefully no ramifications in the code itself?

2024-08-12 12:59 UTC, mks-d commented on readme/paymentmodes.md
> +```
Service prices or payment modes, please re-read and document as it should.

2024-08-12 13:20 UTC, ODORA0 commented on readme/billableservies.md
> +billableservice/
@mks-d Done

2024-08-12 13:20 UTC, ODORA0 commented on readme/billableservies.md
@mks-d Done

2024-08-12 14:28 UTC, Ruhanga commented on api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/BillableServicesLineProcessor.java
> +@OpenmrsProfile(modules = { "billing:1.1.0 - 9.*" })
It’s quite restrictive to specify version 1.1.0 as the required version. We would prefer to set 1.1.0 as the minimum version instead. Version `9.*` provides a more flexible range for usage, accommodating future updates until potential incompatibility issues arise.

2024-08-13 08:49 UTC, mks-d approved these changes

2024-08-13 08:49 UTC, merged