Loading Concept Reference Range Configurations
mekomsolutions/openmrs-module-initializer pull request #287
Opened 2024-12-10 10:29 UTC by wikumChamith

2024-12-11 20:42 UTC, dkayiwa commented on api-2.7/src/test/java/org/openmrs/module/initializer/api/loaders/ConceptReferenceRangeLoaderIntegrationTest.java
> +class ConceptReferenceRangeLoaderIntegrationTest extends DomainBaseModuleContextSensitiveTest {
Why is this class not public?

2024-12-12 17:54 UTC, ibacher commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +	CONCEPT_REFERENCE_RANGE;
Let's move this to immediately after `CONCEPT_SETS`. That seems like a better place.

2025-01-06 10:11 UTC, mks-d requested changes
@wikumChamith thanks for your initiative and work on this.

Could you however edit your PR description [here](https://github.com/mekomsolutions/openmrs-module-initializer/pull/287#issue-2729700655) and detail what this PR brings?

2025-01-06 12:53 UTC, Ruhanga reviewed
Overall, it's looking good @wikumChamith. Just a reminder to conditionally load the api-2.7 packages through the `config.xml` file in the omod sub-module's resources. Here's another minor concern to consider.

2025-01-06 17:42 UTC, ibacher commented on api-2.7/src/main/java/org/openmrs/module/initializer/api/conceptreferencerange/ConceptReferenceRangeLineProcessor.java
> +		conceptReferenceRange
This should have `line.get(HEADER..., true)` since it's an error is the UUID isn't set, right? It also should raise an error if the concept couldn't be found by UUID or if the concept found by that UUID isn't a concept numeric. Can we add some tests for this?

2025-01-06 17:42 UTC, ibacher commented on api-2.7/src/main/java/org/openmrs/module/initializer/api/conceptreferencerange/ConceptReferenceRangeLineProcessor.java
> +	private final String HEADER_CONCEPT_NUMERIC_UUID = "Concept Numeric UUID";
And so on throughout. I think this is more consistent with how things are done:

```suggestion
	private final String HEADER_CONCEPT_NUMERIC_UUID = "Concept numeric uuid";
```

2025-01-06 17:42 UTC, ibacher commented on api-2.7/pom.xml
> +            <version>2.2.0</version>
The version of the FHIR2 module required should be specified as a property, I think. Probably in the base POM than overridden here.

2025-01-06 17:42 UTC, ibacher commented on api-2.7/pom.xml
> +        <groupId>org.openmrs.module</groupId>
nit: When referencing external modules, it should be Group-Artifact-Version.

```suggestion
        <groupId>org.openmrs.module</groupId>
        <artifactId>initializer</artifactId>
```

2025-01-06 17:42 UTC, ibacher commented on api-2.7/src/main/java/org/openmrs/module/initializer/api/conceptreferencerange/ConceptReferenceRangeLoader.java
> +@OpenmrsProfile(openmrsPlatformVersion = "2.7.x")
This doesn't work. Also, add some future-proofing.

```suggestion
@OpenmrsProfile(openmrsPlatformVersion = "2.7.0 - 2.*")
```

2025-01-07 13:54 UTC, wikumChamith commented
@ibacher, @mks-d, @Ruhanga  I updated the PR.

2025-01-07 16:24 UTC, ibacher commented on api-2.7/pom.xml
> +        <fhir2Version2.2>2.2.0</fhir2Version2.2>
Why not just use `fhir2Version`?

2025-01-07 16:24 UTC, ibacher commented on api-2.7/src/test/java/org/openmrs/module/initializer/api/lineprocessor/ConceptReferenceRangeLineProcessorTest.java
> +    public void fill_shouldThrowExceptionForInvalidConceptNumericUuid() {
Could we also add a test for a valid concept UUID that doesn't refer to a `ConceptNumeric`?

2025-01-07 16:24 UTC, ibacher commented on README.md
Can we also update the release notes here?

2025-01-08 07:14 UTC, wikumChamith commented on api-2.7/pom.xml
> +        <fhir2Version2.2>2.2.0</fhir2Version2.2>
When using fhir2Version I am getting an error:

```
[ERROR] Failed to execute goal on project initializer-api-2.7: Could not collect dependencies for project org.openmrs.module:initializer-api-2.7:jar:2.8.0-SNAPSHOT
[ERROR] Failed to read artifact descriptor for org.openmrs.module:fhir2-api-2.1:jar:2.2.0
[ERROR] 	Caused by: The following artifacts could not be resolved: org.openmrs.module:fhir2-api-2.1:pom:2.2.0 (absent): Could not transfer artifact org.openmrs.module:fhir2-api-2.1:pom:2.2.0 from/to repo.mybahmni.org (https://repo.mybahmni.org.s3.amazonaws.com/artifactory/snapshot): Certificate for <repo.mybahmni.org.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]
[ERROR] Failed to read artifact descriptor for org.openmrs.module:fhir2-api-2.2:jar:2.2.0
[ERROR] 	Caused by: The following artifacts could not be resolved: org.openmrs.module:fhir2-api-2.2:pom:2.2.0 (absent): Could not transfer artifact org.openmrs.module:fhir2-api-2.2:pom:2.2.0 from/to repo.mybahmni.org (https://repo.mybahmni.org.s3.amazonaws.com/artifactory/snapshot): Certificate for <repo.mybahmni.org.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]
```

Could this be related to the fhir2 dependencies in the parent POM?

https://github.com/mekomsolutions/openmrs-module-initializer/blob/26222b4811b555136501c026e40b90c86da794d8/pom.xml#L245-L264

2025-01-10 19:29 UTC, ibacher commented on api-2.7/pom.xml
> +        <fhir2Version2.2>2.2.0</fhir2Version2.2>
Oh... right. That's why. Fair enough!

2025-01-10 19:30 UTC, ibacher commented
@mks-d Any objection to merging this in?

2025-01-13 13:04 UTC, merged