Add VisitType domain
mekomsolutions/openmrs-module-initializer pull request #89
Opened 2020-12-17 18:46 UTC by reagan-meant

Need help with 
1. overiding description using only name
2. Voiding concepts using only the name without uuid
3. overide description using uuid

2020-12-17 20:32 UTC, mks-d requested changes
You will also need to add a new entry in [`LoadersIntegrationTest`](https://github.com/mekomsolutions/openmrs-module-initializer/blob/aca9ad4d4356707b0ea717ccfb219546dd0bb7d6/api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersIntegrationTest.java#L48).

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +  VISIT_TYPES(30, "visittypes");
Visit types can presumably be loaded very early, I guess this should work:
```java
VISIT_TYPES(3, "visittypes");
```

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeCsvParser.java
> +public class VisitTypeCsvParser extends CsvParser<VisitType, BaseLineProcessor<VisitType>> {
`VisitTypeCsvParser` → `VisitTypesCsvParser`

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeCsvParser.java
> +		}
This could be done in one line using streams.

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> + * This is the first level line processor for visitTypes. It allows to parse and
In plain English just call them as they are: "visit types" (not "visitTypes").

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> +	 */
This should go.

2020-12-17 20:32 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> +		visitType.setDescription(line.getString(HEADER_DESC, line.getName(true) + " Visit"));
What's going on with the description here?

2020-12-17 20:32 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypeLoaderIntegrationTest.java
> +		}
Add it in [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/aca9ad4d4356707b0ea717ccfb219546dd0bb7d6/api/src/test/resources/testdata/test-metadata.xml), not through code.

2020-12-18 07:04 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> +		visitType.setDescription(line.getString(HEADER_DESC, line.getName(true) + " Visit"));
This is to set a description in case one is not set in the csv

2020-12-18 07:26 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> + * This is the first level line processor for visitTypes. It allows to parse and
Done

2020-12-18 07:26 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/Domain.java
> +  VISIT_TYPES(30, "visittypes");
Done

2020-12-18 07:27 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeCsvParser.java
> +public class VisitTypeCsvParser extends CsvParser<VisitType, BaseLineProcessor<VisitType>> {
Done

2020-12-18 07:27 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeCsvParser.java
> +		}
Done

2020-12-18 07:27 UTC, reagan-meant commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> +	 */
Done

2020-12-18 07:27 UTC, reagan-meant commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypeLoaderIntegrationTest.java
> +		}
Done

2020-12-18 11:16 UTC, mks-d requested changes

2020-12-18 11:16 UTC, mks-d commented on api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersIntegrationTest.java
> +		loader = visitTypeLoader;
`visitTypeLoader` → `visitTypesLoader`

2020-12-18 11:16 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLineProcessor.java
> +		visitType.setDescription(line.getString(HEADER_DESC, line.getName(true) + " Visit"));
Just cater for a description column and do like any other domain would do, encounter types or locations for instance.

2020-12-18 11:16 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypeLoader.java
> +
I forgot that one sorry, `VisitTypeLoader` → `VisitTypesLoader`.

The rule is:
* The loader applies for _all_ visit types.
* The parser applies for _all_ visit types.
* The line processor applies for _one_ visit type at a time.

2020-12-18 11:16 UTC, mks-d commented on api/src/main/java/org/openmrs/module/initializer/api/visittypes/VisitTypesCsvParser.java
> +			        .filter(vt -> vt.getName() == line.getName(true)).findFirst().map(vt -> vt).orElse(null);
Good!

2020-12-18 11:16 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypeLoaderIntegrationTest.java
> +			Assert.assertEquals(true, v.isRetired());
Name them `vt` rather than `v`.

2020-12-21 17:05 UTC, mks-d requested changes

2020-12-21 17:05 UTC, mks-d commented on readme/visittypes.md
> +| - | - | - | - | - | - |
This doesn't display properly because you set 6 columns instead of 5 here:
```md
| - | - | - | - | - |
```

2020-12-21 17:05 UTC, mks-d commented on readme/visittypes.md
> +There is currently only one format for the visittype CSV line, here are the possible headers with a sample data set:
Plain English: `visittype` → `visit type`.

2020-12-21 17:05 UTC, mks-d commented on readme/visittypes.md
> +A Description is used to give more information about the Visit type.
Plain English: `Visit type` → `visit type`.

2020-12-21 17:05 UTC, mks-d commented on readme/visittypes.md
> +<br/>The  Name is a secondary identifier to access a visittype, it will be used to attempt fetching the visit type if no UUID is provided.
Plain English: `visittype` → `visit type`.

2020-12-21 17:05 UTC, mks-d commented on readme/visittypes.md
> +###### Header `Name`
Please specify mandatory fields like here: https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/autogenerationoptions.md#header-identifier-type-mandatory

2020-12-21 17:05 UTC, mks-d commented on api/src/test/resources/testAppDataDir/configuration/visittypes/visittypes.csv
> +xyzf7209-d218-4572-8893-xyz4b5b71934,,RANDOM,RANDOM DESC,
Please provide a valid UUID and values that look like real world examples.

2020-12-21 21:13 UTC, mks-d requested changes
Almost there.

2020-12-21 21:13 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +			Assert.assertEquals("Out Patient Visit", vt.getDescription());
"Outpatient" writes in one word, or you could use "OPD Visit".

2020-12-22 09:36 UTC, mks-d requested changes

2020-12-22 09:36 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +			Assert.assertEquals(1, vts.size());
You should also assert that the name is the one expected for the one visit type that was fetched.

2020-12-22 09:36 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +			Assert.assertNull(vt.getDescription());
Assert the name, that's the main thing to assert after all.
I mean visit types are just three things:
1. A UUID.
2. A name.
3. A description.

In your tests, at minima, when you fetch them by name, assert the UUID, when you fetch by UUID assert the name. That might be different in case of retirements of course.

2020-12-23 07:36 UTC, reagan-meant commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +			Assert.assertNull(vt.getDescription());
Done

2020-12-23 07:36 UTC, reagan-meant commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +			Assert.assertEquals(1, vts.size());
Done

2021-01-04 10:28 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +		}
This is the CSV:
```csv
287463d3-2233-4c69-9851-5841a1f5e109,,OPD,OPD,
```
This shows that the description is in fact `"OPD"`, so how come you assert it to be `"OPD Visit"`?

2021-01-04 11:40 UTC, reagan-meant commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +		}
I am overriding it [here](https://github.com/mekomsolutions/openmrs-module-initializer/pull/89/files#diff-42dd0f50285fb1e647f4943649294052200e36f560b6616998e89d1fb5189dbdR9)

2021-01-04 14:15 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +		}
I see.
Well if you want to make a test that shows that a description can be edited via CSV using the name as a pivot identifier, then you would need to do this:
1. Pre-create the visit type through the test dataset.
2. Have only the final version of the visit type in the CSV file.
3. Assert that what you get in the end is the resulting visit type as per the CSV file.

2021-01-04 14:16 UTC, mks-d requested changes

2021-01-04 14:16 UTC, mks-d commented on api/src/test/java/org/openmrs/module/initializer/api/VisitTypesLoaderIntegrationTest.java
> +		}
I see.
Well if you want to make a test that shows that a description can be edited via CSV using the name as a pivot identifier, then you would need to do this:
1. Pre-create the visit type through the test dataset.
2. Have only the final version of the visit type in the CSV file.
3. Assert that what you get in the end is the resulting visit type as per the CSV file.

2021-01-11 07:38 UTC, rbuisson commented
Hi @mks-d @reagan-meant , is this ready for merge ?

2021-01-11 18:25 UTC, mks-d approved these changes

2021-01-11 19:07 UTC, merged