Throw an IllegalArgumentException if location is specified with a nonexistent parent
mekomsolutions/openmrs-module-initializer pull request #99
Opened 2021-03-31 11:11 UTC by icrc-psousa

**Ticket:** #98 

**Description:** Added the exception when parsing a location with a parent that doesn't exists. If no parent is provided no ex is thrown.

2021-04-06 14:40 UTC, mks-d requested changes

2021-04-07 10:43 UTC, icrc-psousa commented on api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
> +				        "Specified parent location with id '" + parentId + "' for '" + loc.getName() + "' not found ");
Updated exception message

2021-04-07 10:46 UTC, icrc-psousa commented on api/src/test/java/org/openmrs/module/initializer/api/LocationsLoaderIntegrationTest.java
> +		// Verify that location with an invalid parent isn't created
@mks-d I've added this to test loading from csv

2021-04-13 14:24 UTC, mks-d approved these changes

2021-04-13 14:24 UTC, merged